Item14. Comparable을 구현할지 고려하라
TheSwiftists/effective-swift pull request #10
Opened 2020-10-29 11:51 UTC by delmaSong

아이템 14장에 대한 내용을 작성했습니다.
Java에서 Comparable 인터페이스의 역할에 대해 간단하게 알아보고 
그에 대응하는 Swift의 프로토콜에는 Equatable, Comparable, Sequence, IteratorProtocol이 있어 각각의 프로토콜들에 대해 조사했습니다. 
그리고 결론으로는 어떤 상황에 어떤 프로토콜을 채택하면 좋을지 간략하게 정리해 마무리했습니다.

2020-11-02 02:27 UTC, Limwin94 requested changes
잘 읽어보았습니다. :)

2020-11-02 02:27 UTC, Limwin94 commented on chapter3/item14.md
> +print(v1 > v2 ? "true" : "false")			//false
해당 부분 수정한번 부탁드릴게요 :>

2020-11-02 02:37 UTC, Limwin94 approved these changes

2020-11-02 15:13 UTC, dev-Lena approved these changes
각 프로토콜별로 깔끔하게 정리해주셔서 감사합니다!

2020-11-03 23:53 UTC, delmaSong commented
@seizze 바쁘시겠지만 짬날때 리뷰 부탁드립니다,,❣️

2020-11-04 04:13 UTC, seizze commented on chapter3/item14.md
> +- 열거형에서 연관 값 사용 시 Equatable 준수
구조체 커스텀 타입이 Equatable을 준수하게 하려면 그 안의 프로퍼티들도 Equatable을 준수해야 하고, 열거형 커스텀 타입이 Equatable을 준수하게 하려면 그 안의 연관 값들도 Equatable을 준수해야 한다는 의미인가요? 요런 설명을 추가해 주시면 이해가 더 잘 갈것 같아요~! 👍
(만약 이 뜻이 아니라면 조금만 더 풀어서 설명해 주시면 넘 좋을것 같습니당~~ ㅎㅎ)

2020-11-04 04:29 UTC, seizze approved these changes
코멘트 남기긴 했지만 제 리뷰가 늦었기 때문에 빠른 머지를 위해 선프루브 하겠습니다~🔥
반영 여부는 델마님의 선택에 맡기겠습니댜..

2020-11-07 10:40 UTC, merged

2020-11-07 10:40 UTC, delmaSong commented on chapter3/item14.md
> +- 열거형에서 연관 값 사용 시 Equatable 준수
넵 말씀하신대로 설명 추가했습니다 감사합니다 👍🏼