item 57. 지역변수의 범위를 최소화하라
TheSwiftists/effective-swift pull request #100
Opened 2021-02-19 15:42 UTC by dev-Lena

## 내용 소개
9장 일반적인 프로그래밍 원칙이므로 이 문서에서는 책에 소개된 Swift에서도 알아두면 좋은 원칙들을 정리하고 책에 소개된 Java와 Swift의 다른 점을 소개합니다. 

### 요점
 지역변수의 유효 범위를 최소로 줄이면 코드 가독성과 유지보수성이 높아지고 오류 가능성은 낮아집니다.

### 지역변수의 범위를 줄이는 2 가지 기법

#### 1. 지역변수의 범위를 줄이는 가장 강력한 기법은 역시 '가장 처음 쓰일 때 선언하기'입니다.
  - **< 거의 모든 지역변수는 선언과 동시에 초기화해야 합니다. >**
  - **< 반복문은 독특한 방식으로 변수 범위를 최소화해줍니다. >**
    > 반복 변수 (loop variable)의 범위가 반복문의 몸체, 그리고 for 키워드와 몸체 사이의 괄호 안으로 제한됩니다. 따라서 반복 변수의 값을 반복문이 종료된 뒤에도 써야하는 상황이 아니라면 while 문보다 for 문을 쓰는 편이 낫습니다. 
    - 이 내용이 Swift에서도 해당하는지 확인해봅시다.
    - 
#### 2. 메서드를 작게 유지하고 한 가지 기능에 집중하는 것이다.

2021-02-21 15:27 UTC, seizze requested changes
chapter5에 잘못 들어간 item27도 같이 옮기려고 하시는거죠?? 👍
chapter5 디렉토리 삭제도 같이 부탁드릴게요~ (그리고 파일명도 item27.md로 변경 부탁..ㅎㅎ공백이 포함되어 있네용)

2021-05-10 00:29 UTC, ehgud0670 requested changes
수고하셨습니다! 코멘트 부탁드릴게요

2021-05-10 00:29 UTC, ehgud0670 commented on 9장_일반적인_프로그래밍_원칙/item57.md
> +책에 나온 예시
```suggestion
// 책에 나온 예시
```
주석 추가가 필요해보이네요.

2021-05-10 00:29 UTC, ehgud0670 commented on 9장_일반적인_프로그래밍_원칙/item57.md
> +```
* 글쎄요, 자바 코드처럼 numbersIterator2를 만들어 놓으면 잘못 참조할 수 있는 것 같은데요? 따라서 `while 문 보다 for문을 쓰는 편이 낫습니다`는 Swift 에서도 유효한 것 같습니다.
* 다만 swift 의 iterator는 hasNext라는 메서드 없이 next 메서드만 있으므로 잘못된 참조를 덜 할 것 같긴 합니다만, 그럼에도 for 문을 사용하면 while 문 보다 지역변수를 최소화 할 수 있겠네요. 어떻게 생각하시나요?


> 다른 지역 변수 참조가 가능한 while 문
```swift
var numbersIterator = numbers.makeIterator()
var numbersIterator2 = numbers2.makeIterator()
        
while let num = numbersIterator.next() {
    print(num)
}
        
while let num2 = numbersIterator.next() { // 잘못 참조된 numbersIterator (원래는 numbersIterator2를 받아야 한다)
    print(num2) 
}
```

> 다른 지역 변수 참조가 불가능한 for 문 

```swift
for num in numbers.makeIterator() {
    print(num)
}
for num2 in numbers2.makeIterator() {
    print(num2)
}
```

2021-05-16 12:14 UTC, delmaSong approved these changes

2021-05-16 12:14 UTC, delmaSong commented on 9장_일반적인_프로그래밍_원칙/item57.md
> +```
`반복 변수의 값을 반복문이 종료된 뒤에도 써야하는 상황이 아니라면 while 문보다 for 문을 쓰는 편이 낫습니다.` 의 반복변수를 `num`으로 생각했을 때는 레나가 작성해준 말이 맞는 것 같고 반복변수를 `numbersIterator`로 생각했을 때는 제이슨이 들어준 예시가 맞는 것 같군요
두개의 상황을 고려해서 내용이 수정되면 좋을 것 같아요!

2021-05-17 06:06 UTC, ehgud0670 commented on 9장_일반적인_프로그래밍_원칙/item57.md
> +```
반복변수 `num`은 자바 코드에서도 while 문 범위 안에 선언되어 있습니다.
따라서 `numbersIterator` 만 해당하는 사항이니 글 수정하면 좋을 것 같아요. 
특히 `'while 문보다 for 문을 쓰는 편이 낫습니다.'는 Swift에서는 해당하지 않습니다.` 라는 말이 고쳐지면 좋을 것 같네요! 😃

2021-05-31 15:07 UTC, dev-Lena commented on 9장_일반적인_프로그래밍_원칙/item57.md
> +```
제이슨의 의견을 함께 문서에 남겼습니다! 피드백 감사합니다!

2021-05-31 15:18 UTC, ehgud0670 approved these changes
수고하셨습니다. 👍

2021-06-06 12:18 UTC, merged