item45. 스트림은 주의해서 사용해라
TheSwiftists/effective-swift pull request #102
Opened 2021-02-19 16:46 UTC by gwonii

item45 초안입니다.

2021-05-15 09:42 UTC, ehgud0670 reviewed
서식 교정 제안드립니다

2021-05-15 09:42 UTC, ehgud0670 commented on 7장_람다와_스트림/item45.md
> +```
```suggestion
```java
```

서식 교정 합니다~

2021-05-15 09:42 UTC, ehgud0670 commented on 7장_람다와_스트림/item45.md
> +```
```suggestion
```swift
```
여기도요~

2021-05-15 10:18 UTC, ehgud0670 requested changes
스트림 파이프라인 정말 좋은 내용 같습니다. 스트림을 잘 사용하려면 OOP, FP 둘다 일가견이 있어야 될 것 같아요. 필요한건 시간과 노력뿐... 😭
Swift로 코드도 변환하시고 문서 잘 작성하셨네요 👍
그럼 제가 추가로 요청한 내용만 확인 부탁드립니다. 고생하셨습니다!! 👏👏👏

2021-05-15 10:18 UTC, ehgud0670 commented on 7장_람다와_스트림/item45.md
> +
책의 `지연 평가(lazy evaluation)` 내용 매우 좋네요, Rx의 Observable도 결국 지연 평가고(Rx도 스트림 방식이니 당연한 얘기네요 😅). 그래서 지연 평가도 문서에 추가해주십시오 ㅎㅎ 🙏

2021-05-15 10:18 UTC, ehgud0670 commented on 7장_람다와_스트림/item45.md
> +
```suggestion

### 스트림의 장점

적절하게 사용하면 
1. 코드 길이가 짧습니다.
2. 코드가 선언적이고 깔끔해집니다.

### 스트림의 단점

과하게 사용하면 
1. 잘못 사용하면 읽기 어렵습니다.
2. 유지보수가 어려워질 수 있습니다.

```

스트림의 장점과 단점을 제대로 말하려면 조건이 붙어야 할 것 같습니다. 따라서 위처럼 제안드립니다!

2021-05-15 10:18 UTC, ehgud0670 commented on 7장_람다와_스트림/item45.md
> +도우미 메소드를 잘 활용하면 반복적인 코드들을 확실하게 줄이면서 가독성도 높힐 수 있다.
```suggestion
도우미 메소드를 잘 활용하면 반복적인 코드들을 확실하게 줄이면서 가독성도 높힐 수 있습니다.
```
=> 입니다 체로 수정하였습니다.

2021-05-15 10:18 UTC, ehgud0670 commented on 7장_람다와_스트림/item45.md
> +```
```suggestion
```swift
```

2021-05-15 10:18 UTC, ehgud0670 commented on 7장_람다와_스트림/item45.md
> +        Group.init(grouping: words, by: { $0.lowercased().sorted(by: { $0 > $1 }).description })
해당 `lowercased()` 는 자바 코드와 비교해보았을 때 필요없는 코드 같네요~!

2021-05-15 10:18 UTC, ehgud0670 commented on 7장_람다와_스트림/item45.md
> +            .filter { $0.count <= minGroupSize }
다른 부분은 다 잘 해주셨는데 여기 조건은 고쳐야 되겠네여.
```suggestion
            .filter { $0.count >= minGroupSize }
```

2021-05-15 10:18 UTC, ehgud0670 commented on 7장_람다와_스트림/item45.md
> +        .filter { (group) in group.count <= minGroupSize }
```suggestion
        .filter { (group) in group.count >= minGroupSize }
```

2021-05-15 10:18 UTC, ehgud0670 commented on 7장_람다와_스트림/item45.md
> +        })
제 생각에는 책이랑 동일하게 alphabetize 메소드로 대체되어야지만 더 깔끔해진 after 코드라고 할 수 있을 것 같습니다!
왜냐하면 before 코드와 비교해보았을때 한칸 띄운 것 밖에 없어서요(궈니님이 스터디때 말씀하셨던 것처럼 물론 한 칸 띄워서 더 코드가 잘 보이긴 합니다!). 코드를 바꾼다면 alphabetize 메소드도 따로 추가하면 되겠네요.
어떻게 생각하시나요~? 🧐

2021-05-16 12:20 UTC, delmaSong approved these changes
스트림의 장단점을 잘 정리해주신 것 같습니다! 수고하셨습니다 👏🏼
제이슨이 제안해준대로 지연평가에 대한 내용도 보충되면 더 좋을 것 같고 리드미 수정해주세요!

2021-05-30 08:36 UTC, dev-Lena approved these changes
스트림에 대해서 잘 읽었습니다. 제이슨이 리뷰를 잘해주신 것 같네요! 저는 Approve 하겠습니다. 고생하셨습니다! 👍🏻

2023-03-01 06:34 UTC, merged