Item11. equals를 재정의하려거든 hashCode도 재정의하라
TheSwiftists/effective-swift pull request #11
Opened 2020-10-29 15:52 UTC by dev-Lena

### 내용 소개

1. Swift에 대한 내용을 소개하기 전에 먼저 Java에서는 왜 equals와 hashCode는 같이 재정의해야 할지 예제 코드와 함께 설명합니다.
    - equals를 재정의한 후 Java의 컬렉션(Collection) 타입의 자료구조(List, Set)에 넣어보면서 커스텀 타입의 인스턴스들이 논리적으로 같은 객체로 판단되는지 살펴봅시다. 
    - equals 재정의, hashCode 재정의

2. 1번의 과정이 Swift에서는 어떻게 다른지 설명합니다.
    - Equatable 프로토콜 채택, Hashable 프로토콜 채택

2020-11-07 11:23 UTC, delmaSong requested changes
펄풱,, 수고 많으셨습니다 💯 아래 내용만 확인 부탁드려요 !

2020-11-07 11:23 UTC, delmaSong commented on chapter3/Item11.md
> +
** 표시가 한번 더 들어간 것 같습니다!

2020-11-07 11:23 UTC, delmaSong commented on chapter3/Item11.md
> +
이부분 ``` 들여쓰기가 안맞아서 보여지는 문서 상태에서 스타일이 잘 안먹은 것 같아요! 한번 확인 부탁드립니다 🙏🏻

2020-11-07 15:55 UTC, dev-Lena commented on chapter3/Item11.md
> +
피드백 감사합니다! 수정하였습니다 👍🏻

2020-11-07 15:55 UTC, dev-Lena commented on chapter3/Item11.md
> +
이 부분도 수정하였습니다 🙌🏻 감사합니다!

2020-11-07 15:57 UTC, delmaSong approved these changes
수고하셨습니다 👍🏼

2020-11-09 06:05 UTC, seizze approved these changes
자바의 내용을 이해한 후 스위프트 관점에서도 작성해주신 부분이 아주 좋았습니다. 👍

저번 아이템 7의 PR처럼 README.md 파일 변경사항이 사라져 있어서 추가해 놓았습니다~!

2020-11-10 00:53 UTC, Limwin94 approved these changes
고생하셨습니다. 개인사정때문에 리뷰가 늦어진점 죄송합니다 ㅠㅠ

2020-11-10 04:00 UTC, merged