Item44. 표준 함수형 인터페이스를 사용하라
TheSwiftists/effective-swift pull request #114
Opened 2021-03-04 15:51 UTC by ehgud0670

* 자바 표준 함수형 인터페이스에 대응되는 `스위프트 버전 코드`나 `스위프트 버전 함수 시그니처`를 설명하였습니다. 
* 추가로 Swift에서 Predicate 라는 단어(고유명사)가 어떻게 사용되는지 알아보았습니다.
  * Predicate 의 사전적 의미
  * predicate 가 파라미터로 포함된 스위프트 메소드들 
  * NSPredicate 설명

2021-05-16 12:33 UTC, delmaSong requested changes
`표준 함수형 인터페이스를 사용하라`라고 이야기하는데 `왜 그래야하는지?` 에 대한 내용이 적절하게 설명되지(자연스럽게 이어지지) 않은 것 같습니다.! 그리고 Predicate에 대해 깊이 알아보셨는데 여러 인터페이스(시그니처)중 Predicate를 더 깊이 알아보신 이유가 먼저 설명되면 글의 흐름이 더 매끄러워질 것 같습니다! 수고하셨습니다 👏🏼

2021-05-19 05:51 UTC, ehgud0670 commented
넵, 피드백 반영하였습니다. 감사합니다. 😄

2021-05-29 14:28 UTC, dev-Lena approved these changes
predicate 에 대해서 새로 알게 됐습니다! 감사합니다!
함수형 인터페이스에 대해서는 코멘트 하나 남겼습니다! 수고하셨습니다 👍🏻

2021-05-29 14:28 UTC, dev-Lena commented on 7장_람다와_스트림/item44.md
> +사실, 스위프트에는 인수로 함수 객체를 `(인수) -> (반환타입)` 형태로 나타내기 때문에 따로 표준 함수형 인터페이스가 필요없고, 따라서 Predicate니 Supplier니 용어를 알 필요가 자바보다는 적다고 할 수 있습니다.
Java8에서는 함수를 일급객체처럼 다룰 수 있게 함수형 인터페이스를 제공하지만 
Swift에서는 클로저가 이미 일급객체이기 때문에 따로 표현 함수형 인터페이스가 필요없다고 생각하는데요! 
이 내용도 들어가면 좋겠네요!

[참고 자료 - [Java] - @FunctionalInterface 함수형 인터페이스](https://zzang9ha.tistory.com/303)

2021-05-29 15:10 UTC, ehgud0670 commented on 7장_람다와_스트림/item44.md
> +사실, 스위프트에는 인수로 함수 객체를 `(인수) -> (반환타입)` 형태로 나타내기 때문에 따로 표준 함수형 인터페이스가 필요없고, 따라서 Predicate니 Supplier니 용어를 알 필요가 자바보다는 적다고 할 수 있습니다.
자바 8에서도 함수를 이미 일급 객체로 다룹니다. 그리고 함수가 일급 객체이니깐 인수로 함수를 전달할 수 있는 겁니다. 전달할 때 함수 객체 타입을 함수형 인터페이스로 표현할 뿐이죠. 이 부분은 스위프트의 클로저가 이미 일급객체인 것과 똑같습니다.

> 자바 8이 이전 버전과 구별되는 특징 중 하나가 일급 함수를 지원한다는 점이다. (모던 자바 인 액션 p.586)

하지만 스위프트는 표준 함수형 인터페이스가 필요없는 이유는 함수 객체를 파라미터로 표현하는 방법이 스위프트는 자바와 다르고 표현 방식 자체가 표준 함수형 인터페이스가 필요없는 방식이기 때문입니다. 
말씀하시는 것처럼 자바는 스위프트와 달리 해당 함수를 파라미터로 나타날때는 함수형 인터페이스(ex.`Predicate`, `Supplier`) 을 통해 나타내죠. 따라서 전달되는 함수의 `(인수) -> 반환타입`이 같을지라도 여러 개의 이름이 생길수 있는 가능성이 생깁니다. 

> 예시 

```java
interface Predicate<T> {
    boolean test(T t);
}

interface PredicateA<T> {
    boolean test(T t);
}

interface PredicateB<T> {
    boolean test(T t);
}

interface PredicateC<T> {
    boolean test(T t);
}
```
=> 이처럼 같은 `(인수)-> 반환타입`이어도 여러개의 함수형 인터페이스로 나타낼수 있으니 자바에서는 표준 함수형 인터페이스라는 걸 만든 것이고 함수를 전달할 때 **만들어둔 표준 함수형 인터페이스를 쓰라고 하는 것**입니다.
=> 하지만 스위프트는 애초에 함수를 파라미터로 표현할 때 `(인수) -> 반환타입`로 나타내니 `(인수) -> 반환타입`이 중복될 일이 없습니다. 따라서 애초에 겹칠일이 없기 때문에 표준 함수형 인터페이스는 필요가 없는거죠.

2021-05-30 13:29 UTC, dev-Lena commented on 7장_람다와_스트림/item44.md
> +사실, 스위프트에는 인수로 함수 객체를 `(인수) -> (반환타입)` 형태로 나타내기 때문에 따로 표준 함수형 인터페이스가 필요없고, 따라서 Predicate니 Supplier니 용어를 알 필요가 자바보다는 적다고 할 수 있습니다.
아하 그렇군요! 설명 감사합니다! 👍🏻

2021-05-31 10:11 UTC, ehgud0670 commented
왜 표준 함수형 인터페이스를 사용해야 하는지도 설명 추가하였습니다. 😄

2021-05-31 15:36 UTC, merged