Item7. 다 쓴 객체 참조를 해제하라
TheSwiftists/effective-swift pull request #12
Opened 2020-10-29 17:45 UTC by dev-Lena

### 내용 소개

1. Swift에 대한 내용을 소개하기 전에 Java의 Garbage Collection(GC)에 대해 소개합니다.
    - 동작 방식
    - 일반적인 Garbage Collection 대상
    - 장단점

2. Swift의 Automatic Reference Counting(ARC)
    - 동작 방식
    - 레퍼런스 카운트가 오르는 경우
    - 레퍼런스 카운트가 내려가는 경우
    - 장단점

3. 메모리 누수(Memory Leak)에 대해 설명합니다.
    - 메모리 누수는 언제 일어날까?
    - 강한 참조(Strong Reference)와 강한 참조 순환(Reference Cycle) 예시
    - 해결 방법

4. Weak 참조(약한 참조)와 Unowned 참조(미소유 참조)
    - Weak 참조(약한 참조)를 이용한 해결과 설명
    - Unowned 참조(미소유 참조)를 이용한 해결과 설명
    - Strong 참조, Weak 참조, Unowned 참조 비교표

2020-11-03 07:19 UTC, dev-Lena commented
### 수정한 부분
1. ARC 부분에서 GC와 ARC를 비교하는 표현 중 모호한 표현을 수정했습니다.
2. ARC 부분에 예제 코드 변수명 수정했습니다.
3. GC에 대한 설명을 가감했으며 자바 예제 코드를 추가했습니다.
4. 추가적으로 ARC의 동작 방식 중 객체를 제거할 때 런타임에 동기적으로 처리하는지 비동기적으로 처리하는지 조사 후 말씀드리기로 했는데요! 비동기가 맞습니다. 이 부분에 대해서 설명 당시 제가 동기와 비동기에 대해서 혼동해서 그런 것 같아 md 문서에 [동기/비동기에 대해 간단히 설명한 링크](https://stackoverflow.com/a/748235)를 추가했습니다.

2020-11-05 00:20 UTC, seizze requested changes
잘 읽었습니다 💫 내용이 알차네요

근데 아마 충돌 때문에 main에서 가져와서 머지하신 것 같은데 이것 때문에 리드미 변경사항이 사라진것 같아요 ㅠ 마지막 머지 커밋을 수정해 담당자와 링크를 추가하고 올려주시면 깔끔하고 충돌도 해결될것 같습니다~!

2020-11-05 01:32 UTC, Limwin94 approved these changes
GC와 ARC에 대해서 면접용으로도 활용할 수 있을것 같습니다~! 알찬 내용 작성하시느라 고생하셨습니다.

2020-11-07 11:12 UTC, delmaSong approved these changes
많이 배워갑니다 👍🏼

2020-11-08 13:20 UTC, dev-Lena commented
> 잘 읽었습니다 💫 내용이 알차네요
> 
> 근데 아마 충돌 때문에 main에서 가져와서 머지하신 것 같은데 이것 때문에 리드미 변경사항이 사라진것 같아요 ㅠ 마지막 머지 커밋을 수정해 담당자와 링크를 추가하고 올려주시면 깔끔하고 충돌도 해결될것 같습니다~!

넵!🙌🏻 수정했습니다!

2020-11-09 03:21 UTC, seizze approved these changes
수고하셨습니다~~👏👏👏

2020-11-09 03:26 UTC, merged