Item82. 스레드 안정성 수준 문서화
TheSwiftists/effective-swift pull request #123
Opened 2021-04-03 17:30 UTC by dev-Lena

### 작성 내용 
📚 스레드 안전성 문서화
 iOS 에서 'Thread - Safe' 의 의미
 iOS에서의 Multi Thread Programming
 iOS에서의 Multi Thread Programming 체크 리스트 ✅

### 참고

1. [Concurrency Programming Guide](https://developer.apple.com/library/archive/documentation/General/Conceptual/ConcurrencyProgrammingGuide/ConcurrencyandApplicationDesign/ConcurrencyandApplicationDesign.html#//apple_ref/doc/uid/TP40008091-CH100-SW8)
2. [Thread Programming Guide](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Multithreading/ThreadSafety/ThreadSafety.html#//apple_ref/doc/uid/10000057i-CH8-SW1)
3. [atomic/non atomic](https://hcn1519.github.io/articles/2019-03/atomic)
4. [Swift Tip: Atomic Variables](https://www.objc.io/blog/2018/12/18/atomic-variables/)
5. [iOS Developer - Value and Reference Types](https://developer.apple.com/swift/blog/?id=10)
6. [The Readers-Writers Problem (Swift Edition)](https://medium.com/swlh/the-readers-writers-problem-swift-edition-dcba94c3f02d#:~:text=The%20readers%2Dwriters%20problem%20is,writes%20at%20the%20same%20time.)
7. [iOS ) Concurrency Programming Guide - Concurrency and Application Design](https://zeddios.tistory.com/509)
8. [Swift의 메모리 안정성](https://jcsoohwancho.github.io/2019-08-25-Swift%EC%9D%98-%EB%A9%94%EB%AA%A8%EB%A6%AC-%EC%95%88%EC%A0%95%EC%84%B1/)
9. [[iOS] 멀티 스레드(Multi Thread) 구현 시 고려해야될 것들](https://gwangyonglee.tistory.com/47)
10. [Multithreading in iOS with GCD: sync and async operations made easy](

closed #122

2021-05-15 14:25 UTC, ehgud0670 requested changes
iOS 에서의 Multi Thread Programming 체크 리스트도 알려주시고, 도움되는 항목이 많네요!  😁
제 피드백만 확인 부탁드립니다. 수고하셨습니다~! 👍

2021-05-15 14:25 UTC, ehgud0670 commented on 11장_동시성/item82.md
> +어떤 순서로 호출할 때 외부 동기화가 필요한지, 그리고 호출 순서와 관련 lock에 대한 내용을 명시해야합니다. 또한 클래스의 스레드 안전성은 보통 클래스의 문서화 주석에 기재하지만, 독특한 특성의 메서드라면 해당 메서드의 주석에 기재하도록 하는 것을 책에서 권장하고 있습니다.
`어떤 순서로 호출할 때 외부 동기화가 필요한지, 그리고 호출 순서와 관련 lock에 대한 내용을 명시해야합니다.`
=> 이 부분은 **조건부 안전한 클래스** 내용에만 해당하는 부분이라 조건부 안전한 클래스에 대한 문서화 설명이라고 명시해야 할 것 같습니다. 
=> 그럼 뒷 문장 `또한 클래스의 스레드 안전성은 보통 클래스의 문서화 주석에 기재하지만, 독특한 특성의 메서드라면 해당 메서드의 주석에 기재하도록 하는 것을 책에서 권장하고 있습니다.`은 클래스의 스레드 안정성 문서화에 대한 내용이므로 앞문장과 내용이 서로 달라 한칸 띄워야겠네요!

2021-05-15 14:25 UTC, ehgud0670 commented on 11장_동시성/item82.md
> +  * 스레드 적대적 thread-hostile
책처럼 각 항목에 대해 부연 설명 부탁드립니다! 
부연 설명이 있으면 각 항목에 더 이해할 수 있어서 좋은 것 같아요 😁

2021-05-15 14:25 UTC, ehgud0670 commented on 11장_동시성/item82.md
> +### iOS 에서 'Thread - Safe' 의 의미
엄밀히 말하면 iOS 말고도 다른 개발 영역에서도 말이 되는 내용이라 `iOS 에서` 라는 말은 빼도 될 것 같네요!

2021-05-15 14:25 UTC, ehgud0670 commented on 11장_동시성/item82.md
> + - [ ] ✅
```suggestion
 ✅
```
원래 이것만 이렇게 있어야 하는 건가요??

2021-05-15 14:25 UTC, ehgud0670 commented on 11장_동시성/item82.md
> +  Thread-Safe하게 만들기 위해서는 Immutable 한 변수를 고려합니다. Immutable한 인스턴스는 서로 다른 여러 스레드에서 한 번에 접근해도 문제가 되지 않습니다. 즉, Thread-Safe 합니다.
```suggestion
  위와 같은 Readers-Writers problem을 방지하기 위해 그리고 Thread-Safe하게 만들기 위해서는 Immutable 한 변수를 고려합니다. Immutable한 인스턴스는 서로 다른 여러 스레드에서 한 번에 접근해도 문제가 되지 않습니다. 즉, Thread-Safe 합니다. 
```
=> 문장이 안 끝났는데 띄워져서 위처럼 교정하였습니다~

2021-05-30 08:27 UTC, delmaSong approved these changes
swift로 프로그래밍 할 때 스레드와 관련되어 고려 할 사항에 대해 정리를 잘 해주셨네요 👍🏼

2021-05-31 14:30 UTC, dev-Lena commented on 11장_동시성/item82.md
> +어떤 순서로 호출할 때 외부 동기화가 필요한지, 그리고 호출 순서와 관련 lock에 대한 내용을 명시해야합니다. 또한 클래스의 스레드 안전성은 보통 클래스의 문서화 주석에 기재하지만, 독특한 특성의 메서드라면 해당 메서드의 주석에 기재하도록 하는 것을 책에서 권장하고 있습니다.
넵! 피드백 반영하여 수정하였습니다!

2021-05-31 14:30 UTC, dev-Lena commented on 11장_동시성/item82.md
> +  * 스레드 적대적 thread-hostile
🤓 각 스레드 안정성 수준에 대한 부연 설명 추가했습니다!

2021-05-31 14:31 UTC, dev-Lena commented on 11장_동시성/item82.md
> +### iOS 에서 'Thread - Safe' 의 의미
그러네요!

2021-05-31 14:31 UTC, ehgud0670 approved these changes
따봉입니다! 👍 고생하셨어요 👏👏👏

2021-05-31 14:31 UTC, dev-Lena commented on 11장_동시성/item82.md
> + - [ ] ✅
체크리스트같은 느낌을 주고 싶어서 넣었습니다!

2021-05-31 14:31 UTC, dev-Lena commented on 11장_동시성/item82.md
> +  Thread-Safe하게 만들기 위해서는 Immutable 한 변수를 고려합니다. Immutable한 인스턴스는 서로 다른 여러 스레드에서 한 번에 접근해도 문제가 되지 않습니다. 즉, Thread-Safe 합니다.
넵! 반영 완료했습니다!

2021-06-13 02:22 UTC, merged