item76. 가능한 한 실패 원자적으로 만들라
TheSwiftists/effective-swift pull request #124
Opened 2021-04-03 18:42 UTC by delmaSong

일반적인 내용에 초점을 맞춰 작성했습니다

2021-05-15 09:34 UTC, ehgud0670 requested changes
스터디때 델마가 얘기하신것처럼 범용적인 내용이라 굳이 Swift 내용은 안들어가도 될 것 같습니다.
다만 책을 읽어보니 세번째 방법인 `객체의 임시 복사본에서 작업을 수행한 다음, 작업이 성공적으로 완료되면 원래 객체와 교체하기` 가 빠진 것 같은데 실패 원자성을 지키는 방법 중 하나이니 추가 부탁드려요! 
그럼 수고하셨습니다. 잘 읽었어요!! 💯💯💯

2021-05-15 09:34 UTC, ehgud0670 commented on 10장_예외/item76.md
> +
```suggestion
### 실패할 가능성이 있는 모든 코드를 객체의 상태를 바꾸는 코드보다 앞에 배치한다

* 작업 수행에 앞서 매개변수 유효성을 검사하는 것과 비슷한 취지의 방법입니다. 계산을 수행해보기 전에 인수의 유효성을 검사해볼 수 없을 때 앞서의 방식에 덧붙여 쓸 수 있는 기법입니다. 
* 예를 들어 TreeMap을 생각해봅시다. TreeMap은 원소들을 어떤 기준으로 정렬하고, 따라서 TreeMap에 원소를 추가하려면 원소가 TreeMap에 기준에 따라 비교할 수 있는 타입이어야 합니다. 그래서 해당 TreeMap의 원소타입에 맞지 않은 엉뚱한 타입의 원소를 추가하면 **해당 원소가 들어갈 위치를 찾는 과정에서** `ClassCastException`을 던질 것이고 **TreeMap의 상태는 변하지 않을 것**입니다. 
```

`작업 수행에 앞서 매개변수 유효성을 검사한다` 내용 다음에 `실패할 가능성이 있는 모든 코드를 객체의 상태를 바꾸는 코드보다 앞에 배치한다` 라는 내용이 있어서 추가해보았습니다. 해당 내용도 같이 보면 좋을 것 같아서 추가했는데 어떻게 생각하시나요? 🧐

2021-05-16 12:25 UTC, delmaSong commented on 10장_예외/item76.md
> +
저는 `작업 수행에 앞서 매개변수 유효성을 검사하라` 라는 내용에 어느정도 포함되는 내용이라 생각해서 덧붙이지 않았는데, 제안해주신 내용을 추가하면 더 풍성해지겠네요! 좋습니다

2021-05-28 14:16 UTC, dev-Lena approved these changes
실패 원자성에 대해서 알아가네요 감사합니다! 수고하셨습니다!  😃👍🏻

2021-05-30 13:19 UTC, ehgud0670 commented
리뷰 요청하셔서 코멘트 드립니다!
> 세번째 방법인 객체의 임시 복사본에서 작업을 수행한 다음, 작업이 성공적으로 완료되면 원래 객체와 교체하기 가 빠진 것 같은데 실패 원자성을 지키는 방법 중 하나이니 추가 부탁드려요!

이렇게 말씀드렸는데 아직 반영이 안된것 같네여. 반영 부탁드립니다 🙏

2021-05-30 13:37 UTC, delmaSong commented
@ehgud0670 
> 리뷰 요청하셔서 코멘트 드립니다!
> 
> > 세번째 방법인 객체의 임시 복사본에서 작업을 수행한 다음, 작업이 성공적으로 완료되면 원래 객체와 교체하기 가 빠진 것 같은데 실패 원자성을 지키는 방법 중 하나이니 추가 부탁드려요!
> 
> 이렇게 말씀드렸는데 아직 반영이 안된것 같네여. 반영 부탁드립니다 🙏

엇 그렇네요. 반영 완료했습니다! 감사합니다 👍🏼

2021-05-30 13:58 UTC, ehgud0670 approved these changes
수고하셨습니다! 👏👏👏

2021-08-10 07:29 UTC, merged