[WIP] Item 6. 불필요한 객체 생성을 피하라
TheSwiftists/effective-swift pull request #13
Opened 2020-10-30 18:13 UTC by delmaSong

### 주제
> 기존 객체를 재사용해야 한다면 새로운 객체를 만들지 마라

### 목차
- ~~불필요한 객체를 생성하는 경우~~ 하단에 작성된 상세 이유로 인해 목차 변경함
  1. 재사용 가능한 인스턴스를 매번 새롭게 생성하는 경우
    - 책에서는 자바의 String s = new String("hi"); 와 String s = "hi"; 가 별개의 인스턴스라고 하는데 Swift에서 동일하게 생성한 결과 같은 주소값을 나타냄. 그래서 적절하지 않은 예시라 판단.
![스크린샷 2020-10-31 오전 3 01 40](https://user-images.githubusercontent.com/40784518/97740997-6cead000-1b25-11eb-87cc-79cc95640f19.png)
  2. 인스턴스 생성 비용이 높은 객체를 캐시하지 않고 사용하는 경우
  3. ~~정적 초기화 후 호출하지 않는 경우~~ 
    - Swift에서 static init 사용 불가
  4. ~~적절한 타입을 사용하지 않는 경우~~ 
    - Java에선 컬렉션 타입을 감싸는? 오토박싱이란게 있어서 명시적인 컬렉션타입 사용이 아니라 오토박싱을 사용하는 것이 미미한 성능 저하를 유발한다고 함. 허나 Swift에선 엄격하게 타입을 지키도록 하고있어서 저자가 말하는 부적절한 타입(컬렉션 타입 아니라 오토박싱)을 사용하는 사례는 없는 듯.
----
- 객체를 재사용하는 게 좋은 경우
  1. 자주 사용되는 객체의 재사용
  2. 인스턴스 생성 비용이 높은 객체의 재사용
- 그렇다고 객체 생성을 피하고자 객체 풀을 만들지는 말자
- 객체 풀이란?
- 객체 풀을 사용해도 좋은 경우
- 결론

2020-11-01 13:06 UTC, seizze requested changes
수고 많으셨습니다 💯 
자주 사용되는 객체의 재사용 예시 코드 부분만 한번 확인 부탁드려용

2020-11-01 13:06 UTC, seizze commented on chapter2/item6.md
> +```
```swift
class Device {
    private static let sharedInstance: Device = {
        let instance = Device()
        // 디바이스 설정
        return instance
    }()

    private init() { }

    public static func initMethod() -> Device {
        return instance
    }
}
```
return Device()를 하면 항상 새 Device 인스턴스가 생성되어 리턴되는데,
책에서는 위 방식처럼 스태틱 영역에 객체 레퍼런스를 하나 저장해 두고 정적 팩터리 메서드가 불릴 경우 해당 객체를 반환하여 클라이언트에게 재사용하게 하는 방식을 말한 것 같아요~!

2020-11-01 13:06 UTC, seizze commented on chapter2/item6.md
> +
캐시 기능 예시 좋아요 👍 짱

2020-11-01 13:27 UTC, seizze commented
merge 커밋들을 지우려면 item6 브랜치를 main 브랜치에 rebase 후, force push 한번 해주시면 될것 같아용 👍

2020-11-02 08:05 UTC, delmaSong commented on chapter2/item6.md
> +```
wow 완전 반대의 예시를 들고있었네요.. 피드백 감사합니다🙇🏻‍♂️ 최고

2020-11-02 12:49 UTC, delmaSong commented
@seizze @Limwin94 @dev-Lena 피드백 반영 완료했습니다 🙏🏻

2020-11-02 16:40 UTC, dev-Lena approved these changes
깔끔한 설명 감사합니다! 🙌🏻

2020-11-03 05:14 UTC, Limwin94 approved these changes
고생하셨습니다 :>

2020-11-03 12:54 UTC, seizze approved these changes
수고하셨습니다~~ 👏👏👏

2020-11-03 23:53 UTC, merged