Item62 다른 타입이 적절하다면 문자열 사용을 피하라
TheSwiftists/effective-swift pull request #130
Opened 2021-05-15 10:02 UTC by gwonii

2021-05-27 15:12 UTC, ehgud0670 reviewed
일단 인덴트 및 코드만 수정하였습니다. 내용은 디시 살펴볼게요

2021-05-27 15:12 UTC, ehgud0670 commented on 9장_일반적인_프로그래밍_원칙/item62.md
> +```
```suggestion
```swift
// 잘못된 예
struct Person {
    let name: String
    let age: String
} 

let gwonii: Person = .init(name: "gwonii", age: "29")

// 올바른 예
struct Person {
    let name: String
    let age: Int
}

let gwonii: Person = .init(name: "gwonii", age: 29)
```
```

=> 위에 처럼 "twenty-nine"가 아니라 단순히 "29" 아닐까요??
=> 인덴트 수정하였습니다.

2021-05-27 15:12 UTC, ehgud0670 commented on 9장_일반적인_프로그래밍_원칙/item62.md
> +```
```suggestion
```swift
// 잘못된 예
struct Car {
    let type: CarType
    let name: String

    // 2륜, 4륜 등의 구동방식
    let drivingSystem: String
}

let dreamCar: Car = .init(type: .convertible, name: "911", drivingSystem: "2wd")

// 올바른 예
struct Car {
    let type: CarType
    let name: String
    let is4WD: Bool
}

let dreamCar: Car = .init(type: .convertible, name: "911", is4WD: false)
```
```

=> 인덴트 수정하였습니다.

2021-05-27 15:12 UTC, ehgud0670 commented on 9장_일반적인_프로그래밍_원칙/item62.md
> +```
```suggestion
```swift
struct Car {
    let type: CarType
    let name: String
    let drivingSystem: DrivingSystem
}

enum DrivingSystem: CustomStringConvertible {
    case FF
    case FR
    case MR
    case RR
    case 4WD

    var description: String {
	switch self {
	case .FF:
	    return "frontEngineFrontWheel"
	case .FR:
            return "frontEngineRearWheel"
        //... 이하 생략
	}
    }
}
let dreamCar: Car = .init(type: .convertible, name: "911", drivingSystem: .FR)

```
```
=> 인덴트 수정해드렸습니다.

2021-05-27 15:12 UTC, ehgud0670 commented on 9장_일반적인_프로그래밍_원칙/item62.md
> +```
```suggestion
```swift
struct LocalNotificationIdentifer {
    static func isEqualCommuteType(lhs: Self, rhs: Self) -> Bool {
        return lhs.commuteType.rawValue == rhs.commuteType.rawValue
    }

    static func isEqualWeekday(lhs: Self, rhs: Self) -> Bool {
        return lhs.weekday.rawValue == rhs.weekday.rawValue
    }

    let commuteType: CommuteType
    let weekday: Weekday
    let number: Int
}
```
```

2021-05-27 15:12 UTC, ehgud0670 commented on 9장_일반적인_프로그래밍_원칙/item62.md
> +```
```suggestion
```java
public class ThreadLocal {
    private ThreadLocal() { } // 외부에서 객체 생성 불가

    public static void set(String key, Object: value);

    public static Object get(String key);
}

```
```

2021-05-27 15:12 UTC, ehgud0670 commented on 9장_일반적인_프로그래밍_원칙/item62.md
> +```
```suggestion
```java
public class ThreadLocal {
    private ThreadLocal() { } 

    public static class Key { 
        Key() {}
    }

    public static Key getKey() {
        return new Key();	
    }

    public static void set(Key key, Object: value);
    public static Object get(Key key);
}

// ThreadLocal 클래스 자체를 Key값으로 사용하기
public final class ThreadLocal<T> {
    public ThreadLocal();
    public void set(T value);
    public T get();
}
```
```

2021-05-27 15:35 UTC, ehgud0670 approved these changes
잘 읽었습니다. ThreadLocal쪽은 굳이 Swift 예를 찾아볼 필요는 없네요.
수고하셨습니다! 코드 인덴트만 신경써주세요.

2021-05-30 14:31 UTC, delmaSong requested changes
내용 잘 읽었습니다~!
그럼 어떤 경우가 문자열 사용이 적합한 지에 대한 설명도 보충이 되면 좋을 것 같아요
그리고 인덴트랑 포맷팅이 전혀 먹지 않아서.. 이부분 수정 부탁드립니다 😃

2021-05-31 13:47 UTC, dev-Lena approved these changes
범용적인 내용이라 Approve 하겠습니다! 수고하셨습니다! 👏🏻 🤓

2021-05-31 13:47 UTC, dev-Lena commented on 9장_일반적인_프로그래밍_원칙/item62.md
> +위의 코드에서는 Thread 별로 고유한 키값을 맵핑시킬 수 있다. 이로써 Thread의 권한을 적절하게 표현할 수 있게 되었습니다.
```suggestion
위의 코드에서는 Thread 별로 고유한 키값을 맵핑시킬 수 있습니다. 이로써 Thread의 권한을 적절하게 표현할 수 있게 되었습니다.
```

2023-03-01 06:39 UTC, merged