Item65. 리플렉션보다는 인터페이스를 사용하라
TheSwiftists/effective-swift pull request #131
Opened 2021-05-15 10:07 UTC by gwonii

2021-05-27 14:57 UTC, ehgud0670 commented on 9장_일반적인_프로그래밍_원칙/item65.md
> +```
```suggestion
```java
```

2021-05-27 14:57 UTC, ehgud0670 commented on 9장_일반적인_프로그래밍_원칙/item65.md
> +```
```suggestion
```java
```

2021-05-27 15:57 UTC, ehgud0670 approved these changes
자바 리플렉션 찾아봤는데 너무 어렵네여 ㅎㅎ 신기하긴 합니다.
제 생각엔 스위프트의 경우는 안 찾아도 될 것 같습니다.
그럼 수고하셨습니다. 👏👏👏

2021-05-30 06:30 UTC, dev-Lena approved these changes
리플렉션에 대해서 잘 읽었습니다! 👍🏻 Swift에 대한 내용/예시가 있었으면 더 좋았을 것 같습니다! 

리플렉션에서 찾아봤는데 Swift [Mirror](https://developer.apple.com/documentation/swift/mirror)라는 struct, Swift에서의 리플렉션에 대한 [Reflection in Swift](https://www.swiftbysundell.com/articles/reflection-in-swift/) 자료가 있더라구요! 한 번 읽어보면 좋을 것 같아 추천합니다!
고생하셨습니다! 🐝 👏🏻

2021-05-30 14:40 UTC, delmaSong requested changes
잘 읽었습니다! 저도 레나가 제안해주신대로 swift에 관한 내용이 있었으면 좋을 것 같습니다.. 
리드미 추가해주세요

2023-03-01 06:40 UTC, merged