Item69. 예외는 진짜 예외 상황에만 사용하라
TheSwiftists/effective-swift pull request #132
Opened 2021-05-15 10:16 UTC by gwonii

2021-05-27 14:56 UTC, ehgud0670 approved these changes
* 책에서 자바의 경우를 보니 예외적인 상황도 아닌데 런타임 에러를 잡아서 프로그램이 돌아가게 하는 것이 잘못되었다고 얘기하는 내용이군요(ex `무한루프를 돌다가 배열의 끝에 도달해 ArrayIndexOutOfBoundsException이 발생하면 끝을 내는 것이다`).
* 근데 아시다시피 스위프트의 경우에는 런타임 에러를 잡을 수 없습니다. 따라서 스위프트의 경우에는 런타임 에러 자체를 잡을 수 없고, 따라서 스위프트의 경우에는 해당되지 않는다고 깔끔하게 일축시켜도 되겠습니다.

그럼 approve 할테니 위 내용이 동의되시면 내용 수정 부탁드립니다. ㅎㅎ 
잘 읽었습니다~ 👍👍👍

2021-05-27 14:56 UTC, ehgud0670 commented on 10장_예외/item69.md
> +```
```suggestion
```java
```

2021-05-27 14:56 UTC, ehgud0670 commented on 10장_예외/item69.md
> +```
```suggestion
```java
```

2021-05-30 07:22 UTC, dev-Lena approved these changes
잘 읽었습니다! 수고하셨습니다! 👏🏻

2021-05-30 14:53 UTC, delmaSong requested changes
수고하셨습니다! 아래 코멘트 확인해주시고 리드미 수정해주세요!

2021-05-30 14:53 UTC, delmaSong commented on 10장_예외/item69.md
> +
```suggestion

- 애초에 `object(at:)` 라는 메소드에서 throw 처리가 안되어 있기 때문에 `try` 를 사용할 수가 없습니다.

```

2021-05-30 14:53 UTC, delmaSong commented on 10장_예외/item69.md
> +}
```suggestion
for count in countdown {
    print("\(count)...")
}
```

2021-05-30 14:53 UTC, delmaSong commented on 10장_예외/item69.md
> +				let value = try array[index]
왜 배열에 접근할 때 try를 사용하려고 했는지에 대한 내용이 추가되면 글 읽을 때 이해하기 더 수월할 것 같습니다

2022-01-01 10:02 UTC, gwonii commented on 10장_예외/item69.md
> +}
오류 수정하였습니다.

2022-01-01 10:02 UTC, gwonii commented on 10장_예외/item69.md
> +
오류 수정하였습니다.

2022-01-01 10:03 UTC, gwonii commented on 10장_예외/item69.md
> +				let value = try array[index]
예시 코드에서 try 를 시도하려고 하는 이유를 추가하였습니다.

2022-01-01 10:04 UTC, gwonii commented on 10장_예외/item69.md
> +```
code fence에 언어 추가하였습니다.

2022-01-01 10:04 UTC, gwonii commented on 10장_예외/item69.md
> +```
code fence에 언어 추가하였습니다.

2022-01-01 10:22 UTC, merged