item9 내용 작성
TheSwiftists/effective-swift pull request #21
Opened 2020-11-01 13:46 UTC by Limwin94

item9의 내용을 Swift에 알맞게 바꾸어 보았습니다.

현재 finally에서 자원을 회수할때의 의미를 ARC와 맵핑을 하였는데, file stream에서의 자원 회수와 같은 개념으로 다시 맵핑을 하여  보충설명을 해야할것 같습니다.

현재 fileHandle에서 closefile이 deprecated되었는데 해당 사유 또한 참고해보아야 할 것 같습니다.

화요일까지 최대한 빨리 진행해서 올려보도록 하겠습니다 :)

2020-11-05 15:06 UTC, seizze requested changes
좋은 글 잘 읽었습니다. ㅎㅎ File Handler에 대한 내용도 새로 알게되어 좋네요~
README 파일도 수정 부탁드려용⭐️

2020-11-05 15:06 UTC, seizze commented on chapter2/item9.md
> +<br>
아이템 9의 내용을 ARC가 아닌 파일 닫기 등의 개념으로 다시 매핑을 하게 된다면 이 말을

> 책에도 나와 있듯이 finally 구문은 작업이 끝나거나 작업 도중 에러가 발생했을 때 자원을 회수(닫는)하는 용도로 쓰입니다. 스위프트에서도 명시적으로 자원을 닫아주는 작업이 필요할 때가 있는데, 이는 하단에서 다루도록 하겠습니다.

이런 식으로 바꿔보는건 어떨까요? 스위프트에서의 자원 회수 개념으로 매핑할 경우 ARC와 연결짓는게 적합하지 않을 수도 있다는 생각이 들어서요~!

2020-11-05 15:06 UTC, seizze commented on chapter2/item9.md
> +}
중괄호가 안맞는 것 같은디?? 중괄호랑 들여쓰기 조금만 수정 부탁드릴게용 ㅎㅎ

2020-11-05 23:01 UTC, Limwin94 commented on chapter2/item9.md
> +<br>
오 좋은 의견 감사합니다. 해당 구문이 더 자연스럽게 연결되겠네요. 👍

2020-11-05 23:02 UTC, Limwin94 commented on chapter2/item9.md
> +}
넹.. 왜 이렇게 했을까..

2020-11-06 11:44 UTC, seizze approved these changes
쑤고하셨습니다.🔥 (리드미는 수정 안해주셔서 제가해버렸어요..><)

2020-11-06 14:56 UTC, Limwin94 commented
> 쑤고하셨습니다.🔥 (리드미는 수정 안해주셔서 제가해버렸어요..><)

헉 감사합니다!

2020-11-07 11:26 UTC, delmaSong approved these changes
FileHandle 이란 객체가 있는지 처음 알았네요. 수고많으셨습니다 👏🏼

2020-11-09 05:42 UTC, dev-Lena approved these changes
수고하셨습니다~~👏

2020-11-10 14:12 UTC, merged