item12. toString을 항상 재정의하라
TheSwiftists/effective-swift pull request #22
Opened 2020-11-01 13:57 UTC by Limwin94

toString, customStringConvertible과 관련된 함수들, 디버깅을 연결해서 설명해보았습니다.

현장에서 질문을 받았던 부분들 다시한번 코멘트 남겨주시면 고치도록 하겠습니다.
이외 수정사항도 코멘트 남겨주시면 감사하겠습니다 :)

2020-11-01 17:42 UTC, seizze requested changes
이번 주 아이템들까지는 README 파일도 수정해 주셔야 합니다 😭
번거롭지만 수정 부탁드릴게요~

2020-11-01 17:42 UTC, seizze commented on chapter3/item12.md
> +```switf=
코드 블럭들에 swift라고 쓸때 오타가 있어서 컬러링이 안된 것 같아요😢
아래쪽 블럭들도 확인 부탁드립니당~!

2020-11-02 01:26 UTC, Limwin94 commented on chapter3/item12.md
> +```switf=
감사합니다. 수정하겠습니다 :)

2020-11-02 12:58 UTC, delmaSong requested changes
아주 유익한 글이었습니다 👏🏼 수고하셨어요 💯

2020-11-02 12:58 UTC, delmaSong commented on chapter3/item12.md
> +
`자동으로 스트링으로 바뀌는데` 이부분에서
`스트링`을 `String`이나 `문자열`로 변경해주시면 더 통일성 있을 것 같습니다:)

2020-11-03 04:56 UTC, Limwin94 commented on chapter3/item12.md
> +
문맥이랑 단어가 매끄럽지 못했네요 수정하겠습니다. 피드백 감사합니다 :)

2020-11-03 05:11 UTC, seizze approved these changes
수고하셨습니다~ 👏

2020-11-03 13:41 UTC, dev-Lena approved these changes
예시와 함께 설명해주셔서 좋았습니다. 수고하셨습니다! 🙌🏻

2020-11-03 23:54 UTC, delmaSong approved these changes
수고하셨습니다 🧚🏻‍♀️

2020-11-04 00:59 UTC, merged