-니다 체로 변경
TheSwiftists/effective-swift pull request #30
Opened 2020-11-07 12:01 UTC by delmaSong

-니다 체로 변경했습니다

2020-11-07 16:53 UTC, dev-Lena requested changes
몇 군데 추가적으로 수정할 수 있는 부분을 커멘트로 남겼습니다! 🙌🏻

2020-11-07 16:53 UTC, dev-Lena commented on chapter2/item1.md
> +클라이언트가 클래스의 인스턴스를 얻는 전통적인 수단은 public 생성자입니다. 하지만 모든 프로그래머가 꼭 알아둬야 할 기법이 하나 더 있습니다. 클래스는 생성자와 별도로 정적 팩터리 메서드(static factory method)를 제공할 수 있다. 그 클래스의 인스턴스를 반환하는 단순한 정적 메서드입니다.
```suggestion
클라이언트가 클래스의 인스턴스를 얻는 전통적인 수단은 public 생성자입니다. 하지만 모든 프로그래머가 꼭 알아둬야 할 기법이 하나 더 있습니다. 클래스는 생성자와 별도로 정적 팩터리 메서드(static factory method)를 제공할 수 있습니다. 그 클래스의 인스턴스를 반환하는 단순한 정적 메서드입니다. 
```
이 문단에서 한 곳 더 수정할 곳이 있습니다!

2020-11-07 16:53 UTC, dev-Lena commented on chapter2/item1.md
>  - (내가 생각하기에) 이 방법의 장점은 DB 드라이버의 구현체를 아무데서도 명시하지 않아서, 모든 드라이버들이 컴파일은 되지만, Class.forName으로 명시한 클래스만 메모리에 로드되는 것인듯하다.
```suggestion
(내가 생각하기에) 이 방법의 장점은 DB 드라이버의 구현체를 아무데서도 명시하지 않아서, 모든 드라이버들이 컴파일은 되지만, Class.forName으로 명시한 클래스만 메모리에 로드되는 듯합니다.
```
이 부분도 -니다 체로 바꿀 수 있을 것 같습니다!

2020-11-07 16:53 UTC, dev-Lena commented on chapter2/item6.md
> +이번 아이템은 방어적 복사(defensive copy)를 다루는 아이템 50과 대조적입니. 이번 아이템이 **"기존 객체를 재사용해야 한다면 새로운 객체를 만들지 마라"**라면, 아이템 50은 "새로운 객체를 만들어야 한다면 기존 객체를 재사용하지 마라"입니다. **방어적 복사가필요한 상황에서 객체를 재사용했을 때의 피해가, 필요 없는 객체를 반복 생성했
```suggestion
이번 아이템은 방어적 복사(defensive copy)를 다루는 아이템 50과 대조적입니다. 이번 아이템이 **"기존 객체를 재사용해야 한다면 새로운 객체를 만들지 마라"**라면, 아이템 50은 "새로운 객체를 만들어야 한다면 기존 객체를 재사용하지 마라"입니다. **방어적 복사가필요한 상황에서 객체를 재사용했을 때의 피해가, 필요 없는 객체를 반복 생성했을 때의 피해보다 훨씬 크다는 사실을 기억하세요. **방어적 복사에 실패하면 언제 터져 나올지 모르는 버그와 보안 구멍으로 이어지지만, 불필요한 객체 생성은 그저 코드 형태와 성능에만 영향을 줍니다.
```

2020-11-08 00:38 UTC, delmaSong commented
@dev-Lena 최고예요 🤩

2020-11-08 01:32 UTC, dev-Lena approved these changes

2020-11-09 06:36 UTC, seizze approved these changes
수고하셨습니다~~👏👏👏

2020-11-10 00:55 UTC, Limwin94 approved these changes
확인했습니다. 고생하셨습니다 :)

2020-11-10 00:55 UTC, merged