Item5 iOS 활용 예시 수정 및 문체 통일
TheSwiftists/effective-swift pull request #32
Opened 2020-11-07 16:46 UTC by dev-Lena

### 수정한 부분

#4 피드백을 참고하여 Item5를 수정하였습니다.
- 예제 코드: 컴파일 에러가 나는 부분을 해결했습니다.
- iOS 활용 예시: 부적절한 예시는 삭제하고 스터디때 설명한 예시(Property Injection)와 네트워크에 이미지 요청하는 예시(Initializer injection)를 남겨두었습니다.
- 문체를 '-니다'로 통일했습니다.
- 참고한 자료의 링크를 추가했습니다.

2020-11-08 00:41 UTC, delmaSong approved these changes
💯

2020-11-10 13:17 UTC, seizze commented on chapter2/item5.md
> +}
이 부분이 왜 의존성 주입인지 이해가 안가서 한참 보다가 참고 링크를 봤더니
"Without" Dependency Injection 파트의 코드를 실수로 가져오신것 같아여....(?)
확인부탁드림니당 ㅎㅎ

2020-11-10 13:18 UTC, seizze requested changes
짱이에요 👍 
코멘트 남긴 부분만 확인 부탁드릴게용

2020-11-23 14:02 UTC, dev-Lena commented on chapter2/item5.md
> +}
앗 감사합니다!🙌🏻 참고한 글에서 예제를 가져올 때 잘못된 소스 코드를 가지고 왔네요! 확인 후 변경 완료했습니다!

2020-11-26 13:38 UTC, seizze commented
충돌 해결해 놓았습니다~!

2020-11-26 13:39 UTC, seizze approved these changes
충돌 해결을 위해 rebase했습니다~!

2020-11-29 13:48 UTC, Limwin94 approved these changes
고생하셨습니다 👍🏻

2020-11-30 12:35 UTC, merged