Item21. 인터페이스는 구현하는 쪽을 생각해 설계하라
TheSwiftists/effective-swift pull request #36
Opened 2020-11-13 11:59 UTC by dev-Lena

### 내용 소개

1. 책에서 권고하는 Java에서의 인터페이스 구현 방향 요약
2. 제가 생각하는 Swift에서의 프로토콜 구현 방향 간단히 언급 (Protocol + extension / Delegation 패턴)
3. iOS 예시 소개 -  UIAppDelegate

+ 예제가 적절한지와 protocol + extension을 통한 기본구현에 대해 스터디 때 이야기 나누면 좋을 것 같습니다.

2020-11-14 09:04 UTC, delmaSong requested changes
아까 말씀드렸듯이 기본 구현된 프로토콜의 메서드를 개발자가 불러와 사용하는 예제면 더 적합할 것 같습니다 🐝

2020-11-23 05:50 UTC, dev-Lena commented
### 스터디 이후 수정한 내용

1. Delegation 내용 및 UIAppDelegate 메서드 예시가 적절하지 않다고 생각해서 삭제했습니다.
2. 프로토콜 기본 구현에 대한 내용을 추가했습니다.
  - protocol default implementation 소개
  - protocol default implementation 간단한 예제
  - protocol default implementation 고려해야할 점

2020-11-28 10:27 UTC, delmaSong approved these changes
자바의 default method와 대응하는 protocol extension에 대해 잘 정리해주셨네요 👍🏼
아래 부분만 확인해주세요!

2020-11-28 10:27 UTC, delmaSong commented on chapter4/item21.md
> +extension Double: TextRepresentable { }
`TextRepresentable`의 `describeSelf`의 getter를 구현해주어야하지 않나요?
빈상태로 두면 아마 컴파일 에러가 날 것 같슴다

2020-11-28 10:27 UTC, delmaSong commented on chapter4/item21.md
> +1. [[Adding Protocol Conformance with an Extension - The Swift Programming Language](https://docs.swift.org/swift-book/LanguageGuide/Protocols.html#ID276)
[ 가 한번 더 쓰여졌네용

2020-11-30 13:22 UTC, dev-Lena reviewed
피드백 주신 부분 수정완료했습니다! 🐝

2020-11-30 13:22 UTC, dev-Lena commented on chapter4/item21.md
> +extension Double: TextRepresentable { }
앗 네! 이 상태로는 컴파일 에러가 납니다. 자세한 구현부는 생략하고 작성한 예제 코드인데 보는 분은 헷갈릴 수 있겠네요! 자세한 구현은 생략한다는 주석을 남기도록 하겠습니다! 피드백 감사합니다 👍

2020-11-30 13:22 UTC, dev-Lena commented on chapter4/item21.md
> +1. [[Adding Protocol Conformance with an Extension - The Swift Programming Language](https://docs.swift.org/swift-book/LanguageGuide/Protocols.html#ID276)
네! 이 부분 수정해야겠네요!

2020-11-30 13:25 UTC, dev-Lena commented
### 추가한 부분

이번 주제와 관련해서 JK에게 의견을 물어봤었는데요.
JK와 이야기(?)했던 내용을 반영하여서 내용의 흐름을 조금 수정했고 결론을 추가했습니다!

2020-12-05 05:40 UTC, seizze approved these changes
프로토콜의 기본 구현에 대한 새로운 내용을 알게 되어 좋았습니다.
글 잘 읽었습니다~~ 👏👏👏

2020-12-07 12:47 UTC, Limwin94 requested changes
스터디때 언급 되었던 프로토콜 재정의 부분만 수정해서 올려주시면 될 것 같습니다 👍🏻

2020-12-07 12:47 UTC, Limwin94 commented on chapter4/item21.md
> +또한 기존에 제공되는 프로토콜들의 익스텐션을 통한 기본 구현 코드를 볼 수는 없지만, 공개되어있는 내부 구현을 살펴봤을 때 스위프트의 많은 기능들이 프로토콜, 익스텐션, 제네릭의 조합으로 구현되어 있는 것 같습니다. 그 중에서 한 가지 예를 들어 살펴보자면, `Array`, `Set`, `Dictionary` 에서 공통으로 채택하고 있는 프로토콜들은 `C
`CustomDebugStringConvertible`이 중복된것 같습니다.

2020-12-07 12:47 UTC, Limwin94 commented on chapter4/item21.md
> +   * 우선 순위: *프로토콜을 준수한 class/struct/enum-> 제약이 있는 protocol extension -> 단순 protocol extension*.
스터디때 언급되었던 부분입니다. 대소 비교나 우선 순위를 더 명확하게 나타내주는 표현으로 바꾸면 좋을 것 같습니다!

2020-12-24 11:10 UTC, Limwin94 approved these changes

2020-12-24 11:11 UTC, merged

2021-01-05 03:20 UTC, dev-Lena commented
이번 아이템에서 언급한 method dispatch(dynamic dispatch  static dispatch)에 대한 WWDC 영상입니다. 참고하면 더 좋을 것 같습니다 👍 

![image](https://user-images.githubusercontent.com/52783516/103602869-71ca6680-4f50-11eb-8f77-3c4809634e82.png)

[WWDC 2015 Understanding Swift Performance](https://developer.apple.com/videos/play/wwdc2016/416/?time=1097) 
18:00~