[WIP] item15. 클래스와 멤버의 접근 권한을 최소화 하라.
TheSwiftists/effective-swift pull request #48
Opened 2020-11-23 12:56 UTC by Limwin94

자체적으로 내용을 보충할것이나, 이전 만남때 부족한 부분들 리뷰로 남겨주시면 해당 리뷰 참고하여 추가 보충하도록 하겠습니다.

2020-11-24 06:50 UTC, dev-Lena requested changes
고생하셨습니다! 코멘트 단 부분만 수정해주시면 좋을 것 같습니다.
그리고 스터디 때도 잠깐 언급했었는데요!
 [이 내용](https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html#ID17)도 있으면 좋을 것 같네요:) 🐝

2020-11-24 06:50 UTC, dev-Lena commented on chapter4/item15.md
> +(자바와 마찬가지로 밑으로 갈수록 접근 범위가 좁아집니다.)
밑으로 갈수록 접근 범위가 넓어지는 것 같습니다! 😋

2020-11-24 06:52 UTC, Limwin94 commented on chapter4/item15.md
> +(자바와 마찬가지로 밑으로 갈수록 접근 범위가 좁아집니다.)
이부분 저녁때 수정하도록 하겠습니다 :) 코멘트 감사합니다.

2020-11-24 06:53 UTC, Limwin94 commented
> 고생하셨습니다! 코멘트 단 부분만 수정해주시면 좋을 것 같습니다.
> 그리고 스터디 때도 잠깐 언급했었는데요!
> [이 내용](https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html#ID17)도 있으면 좋을 것 같네요:) 🐝

혹시 해당내용 중에 범위를 좁혀주실수 있을까요?

2020-11-24 06:54 UTC, dev-Lena commented
> > 고생하셨습니다! 코멘트 단 부분만 수정해주시면 좋을 것 같습니다.
> > 그리고 스터디 때도 잠깐 언급했었는데요!
> > [이 내용](https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html#ID17)도 있으면 좋을 것 같네요:) 🐝
> 
> 혹시 해당내용 중에 범위를 좁혀주실수 있을까요?

`fileprivate(set)`, `private(set)`, `internal(set)` 에 대한 내용이요!

2020-11-24 07:01 UTC, Limwin94 commented
> > > 고생하셨습니다! 코멘트 단 부분만 수정해주시면 좋을 것 같습니다.
> > > 그리고 스터디 때도 잠깐 언급했었는데요!
> > > [이 내용](https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html#ID17)도 있으면 좋을 것 같네요:) 🐝
> > 
> > 
> > 혹시 해당내용 중에 범위를 좁혀주실수 있을까요?
> 
> `fileprivate(set)`, `private(set)`, `internal(set)` 에 대한 내용이요!
> 이 내용은 추가적인 내용인 것 같아서 Limwin님이 판단하고 결정하시면 될 것 같아요!
> 저의 작은 의견이었답니다 :)

아하 넵, 해당 문서도 잘 읽어보고 정리해서 추가하도록 하겠습니다.
감사합니다 :>

2020-11-28 09:46 UTC, delmaSong commented on chapter4/item15.md
> +
`package-private` 으로 수정해주세요

2020-11-28 09:46 UTC, delmaSong commented on chapter4/item15.md
> +- open
개별 항목에 대한 세부적인 설명이 추가되면 좋을 것 같습니다:)

2020-11-28 09:46 UTC, delmaSong commented on chapter4/item15.md
> +
스레드 안전하지 않은 예시가 추가되면 좋을 것 같아요 🙂

2020-11-29 08:53 UTC, seizze approved these changes
수고하셨습니다~~👏👏👏

2020-11-29 13:32 UTC, Limwin94 commented on chapter4/item15.md
> +
넵 알겠습니다.

2020-11-29 13:32 UTC, Limwin94 commented on chapter4/item15.md
> +- open
짧게 요약해서 설명 추가하도록 하겠습니다.

2020-11-29 13:32 UTC, Limwin94 commented on chapter4/item15.md
> +
넵 ☺️

2020-12-18 05:33 UTC, Limwin94 commented on chapter4/item15.md
> +
접근제한자가 public이라 thread unsafety한것이 아니라 '가변'이기 때문이라고 생각합니다.

내부에 private으로 선언되었어도 해당 변수의 값을 변경하는 setter역할을 하는 메소드가 있으면 역시 thread unsafety하기 때문입니다.

본문에서도 참고할만한 링크와 의견을 좀 더 수정하여 작성하겠습니다.

2020-12-19 14:03 UTC, delmaSong approved these changes
수고하셨습니다 🔥

2020-12-19 14:03 UTC, delmaSong commented on chapter4/item15.md
> +
오타가 있네요ㅠ
```suggestion
이번 아이템의 내용 중 package-private에 대한 내용들이 있어 자바의 패키지와 대치되는 스위프트의 프레임워크와 open, public을 묶어 설명하려 하였습니다.

```

2020-12-24 11:13 UTC, dev-Lena approved these changes
고생하셨습니다 🔥

2020-12-24 11:13 UTC, merged