Item27. 비검사 경고를 제거하라
TheSwiftists/effective-swift pull request #49
Opened 2020-11-23 13:57 UTC by dev-Lena

### 내용 소개

1. Java에서의 _ClassCastException_에 대해 간단히 소개합니다.
2. Swift의 타입 캐스팅에 대해 간략히 소개 후 런타임 오류가 발생하는 경우(as!)를 예시와 함께 설명합니다.
3. 2번의 경우를 어떻게 해야하는지 소개합니다(as?)
4. 타입 캐스팅을 할 때 Xcode의 경고 메세지을 어떻게 바라봐야 하는지에 대한 짧은 의견을 남겼습니다.

closes #45

2020-12-06 11:56 UTC, delmaSong approved these changes
`비검사 경고란 무엇인지` 가 추가되면 좋을 것 같아요~!
비검사 경고가 Xocde에서 yellow warning 띄워주는거랑 비슷하려나요?
꼭 그랬으면 하는 건 아니고 제안인데 타입캐스팅 외에도 yellow warning이 띄워지는 경우에 대한 내용이 좀 더 보충되면 좋을 것 같습니다..ㅎㅎ

2020-12-24 16:32 UTC, dev-Lena commented
> `비검사 경고란 무엇인지` 가 추가되면 좋을 것 같아요~!
> 비검사 경고가 Xcode에서 yellow warning 띄워주는거랑 비슷하려나요?
> 꼭 그랬으면 하는 건 아니고 제안인데 타입캐스팅 외에도 yellow warning이 띄워지는 경우에 대한 내용이 좀 더 보충되면 좋을 것 같습니다..ㅎㅎ

비검사 경고에 대한 설명을 추가했습니다!
비검사 경고는 Xcode에서와 같이 컴파일러에서 발생하는 경고(Warning)입니다!

델마님의 제안 너무 감사하지만 경우의 수가 너무 많고 자료를 찾기 어려워 타입캐스팅 외의 yellow warning이 띄워지는 경우에 대한 내용은 추가하기 어려울 것 같습니다. ㅠㅠ 하지만 제안 감사합니다!

2021-01-05 04:46 UTC, Limwin94 approved these changes
고생하셨습니다.

2021-01-08 13:44 UTC, ehgud0670 requested changes

2021-01-08 13:44 UTC, ehgud0670 commented on chapter5/item 27.md
> +
* 자바는 경고를 통해 타입 불안정성을 알려주지만, 스위프트는 컴파일 오류를 통해 타입 불안전함을 알려준다고 자바와 비교되게 내용 설명하는 건 어떠신가요? 그래서 컴파일 에러를 없애고 as! 가 아닌 as? 만 사용하면 스위프트는 타입으로 인한 런타임 오류는 없다고 설명되었으면 좋겠습니다.
* 그리고 자바의 비검사 경고는 잠재적으로 런타임 에러 가능성이 있는 코드를 경고하지만, 이와 달리 스위프트의 타입 캐스팅 관련 경고들은 직접적으로 런타임 에러 가능성이 나는 부분이 아니지만 교정해야 하는 부분(ex.`as를 써도 되는 부분에 as? 를 쓴 경우`, `타입이 서로 상관이 없어 타입 캐스팅이 항상 실패하는 경우`)을 알려주는 역할을 한다고 이 또한 자바와 비교되게 내용 추가되었으면 좋겠습니다.

=> 자바와 달리 스위프트는 경고가 아닌 컴파일 에러를 통해 타입 안정성을 체크하고, 또 스위프트의 타입 캐스팅 관련 경고(warning)들은 런타임 에러 가능성를 내포하는게 아니라는 점이 보였으면 좋겠어서 피드백 드립니다 ㅎㅎ  지금 글로만 읽으면 스위프트도 경고들이 런타임 에러 가능성을 내포한다고 이해되고, 컴파일오류 없고 as?를 습관화해도 런타임 에러 가능성이 있을 수 있다고 이해가 되어서요.

 늦게 읽어 죄송합니다. ㅠ 좋은 글 잘 읽었습니다 😀

2021-01-10 09:47 UTC, seizze commented on chapter5/item 27.md
> +
> 스위프트의 타입 캐스팅 관련 경고(warning)들은 런타임 에러 가능성를 내포하는게 아니라는 점

이말 진짜 좋네여 💯 약간 헷갈렸는데 정리가 명확히 됐어요

자바에서 제네릭을 사용할 때 경고로 알려줬던 부분들을 스위프트에서는 에러로 확실히 나타내 줘서 강제성을 더 띈다는 점이 핵심인 것 같습니다. 자바도 에러로 알려주면 더 좋을 텐데, 하위 호환을 위한 로 타입 때문에 어쩔 수 없이 경고로 알려주는 것 같다는 생각도 들었고요. 스위프트는 자바처럼 제네릭 이전 작성된 코드가 없어 하위 호환을 지킬 필요가 없기 때문에 로 타입이 없어서 에러로 알려줄 수 있는 것 같아요~

2021-01-10 09:48 UTC, seizze approved these changes
수고하셨습니다~~👏👏👏

2021-02-09 10:14 UTC, dev-Lena commented
@ehgud0670 

피드백 감사합니다!👍🏻 해당 내용 추가했습니다! 확인 부탁드립니다!!

2021-02-10 01:15 UTC, ehgud0670 commented on chapter5/item 27.md
> +덧붙여, Java의 비검사 경고와 같이 Xcode에서도 타입 캐스팅을 시도할 때 경고 메세지를 띄워주기도 합니다. 이 경고 메세지를 제거한다고 타입 캐스팅에서 일어날 수 있는 모든 런타임 오류를 해결할 수는 없지만 경고 메세지를 확인하며 타입 캐스팅에 대해 올바른 연산자를 사용하고 있는지 현재 캐스팅하려고 하는 타입들이 서로 호환 가능한지 다시 돌아보는
논의한 바대로 `모든 런타임 오류를 해결할 수는 없지만`라는 말은 부적절 해보입니다. 
모든 경고 메시지와 컴파일 오류를 해결하면 타입 캐스팅 관련 런타임 에러는 해결될 것 같아요.

2021-02-10 06:21 UTC, dev-Lena commented on chapter5/item 27.md
> +덧붙여, Java의 비검사 경고와 같이 Xcode에서도 타입 캐스팅을 시도할 때 경고 메세지를 띄워주기도 합니다. 이 경고 메세지를 제거한다고 타입 캐스팅에서 일어날 수 있는 모든 런타임 오류를 해결할 수는 없지만 경고 메세지를 확인하며 타입 캐스팅에 대해 올바른 연산자를 사용하고 있는지 현재 캐스팅하려고 하는 타입들이 서로 호환 가능한지 다시 돌아보는
넵 아래 추가한 내용으로 대체할 수 있다고 생각해서 해당 문단 삭제했습니다!

2021-02-10 06:43 UTC, ehgud0670 commented on chapter5/item 27.md
> +Java는 제네릭을 사용할 때 경고를 통해 타입 불안정성을 알려주지만, Swift는 경고가 아닌 컴파일 오류를 통해 타입 불안전성을 더 확실히 알려줍니다. 덧붙여 Java의 비검사 경고는 잠재적으로 런타임 에러 가능성이 있는 코드를 경고하지만, 이와 달리 Swift의 타입 캐스팅 관련 경고들은 직접적으로 런타임 오류 가능성이 나는 부분은 아니지만 교정해야
```suggestion
Java는 제네릭을 사용할 때 경고를 통해 타입 불안정성을 알려주지만, Swift는 경고가 아닌 컴파일 오류를 통해 타입 불안전성을 더 확실히 알려줍니다. 덧붙여 Java의 비검사 경고는 잠재적으로 런타임 에러 가능성이 있는 코드를 경고하지만, 이와 달리 Swift는 **런타임 에러 가능성을 컴파일 오류로 모두 알려주기 때문에** 타입 캐스팅 관련 경고들은 런타임 오류 가능성이 나는 부분이 아닌 교정해야 하는 부분(ex.`as를 써도 되는 부분에 as? 를 쓴 경우`, `타입이 서로 상관이 없어 타입 캐스팅이 항상 실패하는 경우`)을 알려주는 역할을 합니다. Swift의 타입 캐스팅 관련 경고(warning)들은 런타임 오류 가능성를 내포하지 않습니다. 
```
=> 위처럼 덧붙이면 Swift 의 타입 캐스팅 관련 경고가 왜 런타임 에러 가능성을 내포하지 않는지에 대한 이유가 명확해지는 것 같아서 제안합니다.

2021-02-10 12:46 UTC, dev-Lena commented on chapter5/item 27.md
> +Java는 제네릭을 사용할 때 경고를 통해 타입 불안정성을 알려주지만, Swift는 경고가 아닌 컴파일 오류를 통해 타입 불안전성을 더 확실히 알려줍니다. 덧붙여 Java의 비검사 경고는 잠재적으로 런타임 에러 가능성이 있는 코드를 경고하지만, 이와 달리 Swift의 타입 캐스팅 관련 경고들은 직접적으로 런타임 오류 가능성이 나는 부분은 아니지만 교정해야
넵 반영해 커밋했습니다!

2021-02-11 02:35 UTC, ehgud0670 commented on chapter5/item 27.md
> +Java는 제네릭을 사용할 때 경고를 통해 타입 불안정성을 알려주지만, Swift는 경고가 아닌 컴파일 오류를 통해 타입 불안전성을 더 확실히 알려줍니다. 덧붙여 Java의 비검사 경고는 잠재적으로 런타임 에러 가능성이 있는 코드를 경고하지만, 이와 달리 Swift의 타입 캐스팅 관련 경고들은 직접적으로 런타임 오류 가능성이 나는 부분은 아니지만 교정해야
감사합니다!

2021-02-11 02:36 UTC, ehgud0670 approved these changes

2021-02-11 02:37 UTC, ehgud0670 commented
수고하셨습니다! 👍👍👍

2021-02-11 03:18 UTC, merged