item22. 인터페이스는 타입을 정의하는 용도로만 사용하라
TheSwiftists/effective-swift pull request #51
Opened 2020-12-02 16:39 UTC by delmaSong

- Java의 Interface
- Swift의 Protocol
  - 프로토콜을 사용하는 4가지 카테고리에 대해 정리
- 결론 및 요약

2020-12-26 16:37 UTC, seizze approved these changes
수고하셨습니다~~👏👏👏

2020-12-27 10:50 UTC, dev-Lena approved these changes
`모든 프로토콜을 동일한 방식으로 취급하는 것이 아니라 어떤 카테고리에 속하는지에 따라 디자인 하는 것이 중요합니다.` 기억하겠습니다. 👍🏻
프로토콜의 4가지 용법과 팁 그리고 Apple의 프레임워크에서 어떻게 구현되어있는지 델마님 덕분에 자세히 알게 되었습니다. 알찬 내용 감사합니다. 👏🏻

고생하셨습니다 🐝✨

2020-12-27 10:50 UTC, dev-Lena commented on 4장_클래스와_인터페이스/item22.md
> +- **Type conversion** : `CustonStringConvertible`, `ExpressibleByStringLiteral` 처럼다양한 유형이 다른 유형으로 변환 가능하거나 원시 값 또는 리터럴을 통해 표현할 수 있음을 선언하는데 사용
오타가 있는것 같습니다!
`CustonStringConvertible` -> `CustomStringConvertible`

2020-12-27 16:21 UTC, ehgud0670 requested changes
내용이 매우 풍부해서 재밌게 잘 봤습니다.
많이 배우고 갑니다 :)

2020-12-27 16:21 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item22.md
> +특정한 작업을 수행하기 위해 이를 준수하는 타입이 필요한 프로토콜부터 살펴보겠습니다. 예를들어 표준 라이브러리인 `Equatable` 프로토콜은 두 인스턴스간에 동등성 검사를 수행할 수 있음 표시하는 데 사용되는 반면 `Hashable` 프로토콜은 해시될 수 있는 유형에 의해 채택됩니다.
```suggestion
특정한 작업을 수행하기 위해 이를 준수하는 타입이 필요한 프로토콜부터 살펴보겠습니다. 예를들어 표준 라이브러리인 `Equatable` 프로토콜은 두 인스턴스간에 동등성 검사를 수행할 수 있음을 표시하는 데 사용되는 반면 `Hashable` 프로토콜은 해시될 수 있는 유형에 의해 채택됩니다.
```
`을` 을 추가하는게 맞는거죠?

2020-12-27 16:21 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item22.md
> +그러나 모든 프로토콜이 동작을 정의하는 건 아닙니다. 예를들어, 아래의 `Cacheable` 프로토콜의 이름은 캐싱 작업이 포함되어있음을 암시하지만 실제로는 다양한 유형이 자체 캐싱 키를 정의할 수 있도록 하는데 사용됩니다.
```suggestion
그러나 모든 프로토콜이 동작을 정의하는 건 아닙니다. 예를들어, 아래의 `Cachable` 프로토콜의 이름은 캐싱 작업이 포함되어있음을 암시하지만 실제로는 다양한 유형이 자체 캐싱 키를 정의할 수 있도록 하는데 사용됩니다.
```
철자요 ㅎㅎ

2020-12-27 16:21 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item22.md
> +위의 `Sequence`와 `IteratorProtocol`을 염두에 두고 `Cacheable`과 `Colorable` 프로토콜로 돌아가 요구사항을 담고 있는 프로토콜로서 개선할 수 있는지 살펴보겠습니다.
```suggestion
위의 `Sequence`와 `IteratorProtocol`을 염두에 두고 `Cachable`과 `Colorable` 프로토콜로 돌아가 요구사항을 담고 있는 프로토콜로서 개선할 수 있는지 살펴보겠습니다.
```
철자요! ㅎㅎ

2020-12-27 16:21 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item22.md
> +> 자체 코드 내에서 대부분의 기본 제공 리터럴 프로토콜을 자유롭게 준수 할 수 있지만, `ExpressibleByNilLiteral` 준수는 권장되지 않습니다. - 'Optional'은 해당 프로토콜을 채택하는 유일한 유형이 될 것으로 예상됩니다.
```suggestion
> 자체 코드 내에서 대부분의 기본 제공 리터럴 프로토콜을 자유롭게 준수 할 수 있지만, `ExpressibleByNilLiteral` 준수는 권장되지 않습니다. - 'Optional'은 해당 프로토콜을 채택하는 유일한 유형이 될 것으로 예상됩니다. ( `@frozen public enum Optional<Wrapped> : ExpressibleByNilLiteral` )
```

=> 혹시 이런 식으로 코드로도 추가 설명 되실까요? 
처음에 글로만 보고는 이해가 완벽히 되지 않았는데 코드를 찾아서 보고 완전히 이해가 되어서요 ㅎㅎ
혹 저 같은 사람을 위해 위처럼 코드도 추가 가능한지 제안해봅니다~~

제안이니 리젝하셔도 됩니다 ㅋㅋ

2020-12-28 12:13 UTC, delmaSong commented on 4장_클래스와_인터페이스/item22.md
> +    var cacheKey: String { get }
```suggestion
protocol Cacheable: Codable {
    var cacheKey: String { get }
```

2020-12-28 12:13 UTC, delmaSong commented on 4장_클래스와_인터페이스/item22.md
> +
```suggestion

위의 `Sequence`와 `IteratorProtocol`을 염두에 두고 `Cacheable`과 `Colorable` 프로토콜로 돌아가 요구사항을 담고 있는 프로토콜로서 개선할 수 있는지 살펴보겠습니다.

```

2020-12-28 12:13 UTC, delmaSong commented on 4장_클래스와_인터페이스/item22.md
> +그러나 모든 프로토콜이 동작을 정의하는 건 아닙니다. 예를들어, 아래의 `Cacheable` 프로토콜의 이름은 캐싱 작업이 포함되어있음을 암시하지만 실제로는 다양한 유형이 자체 캐싱 키를 정의할 수 있도록 하는데 사용됩니다.
cacheable이 맞는 표현이네요 내부 프로토콜 이름을 수정했습니다 ㅎㅎ

2020-12-28 12:16 UTC, delmaSong commented on 4장_클래스와_인터페이스/item22.md
> +- **Type conversion** : `CustonStringConvertible`, `ExpressibleByStringLiteral` 처럼다양한 유형이 다른 유형으로 변환 가능하거나 원시 값 또는 리터럴을 통해 표현할 수 있음을 선언하는데 사용
```suggestion
- **Type conversion** : `CustomStringConvertible`, `ExpressibleByStringLiteral` 처럼다양한 유형이 다른 유형으로 변환 가능하거나 원시 값 또는 리터럴을 통해 표현할 수 있음을 선언하는데 사용
```

2020-12-28 12:22 UTC, ehgud0670 approved these changes
Excellent! 훌륭합니다

2020-12-28 12:52 UTC, seizze approved these changes
다들 눈이 좋으시넹 👁

2021-01-03 13:58 UTC, Limwin94 approved these changes
고생하셨습니다. 해당 부분만 수정 후 머지하면 될것 같습니다!

2021-01-03 13:58 UTC, Limwin94 commented on 4장_클래스와_인터페이스/item22.md
> +이 지침에 맞지 않는 예로 소위 상수 인스턴스라는 것이 있습니다. 상수 인스턴스란 메서드 없이, 상수를 뜻하는 static final 필드로만 가득 찬 인터페이스를 말합니다. 그리고 이 상수들을 사용하려는 클래스에서는 정규화된 이름(qualified name)을 쓰는 걸 피하고자 그 인터페이스를 구현하곤 합니다.  다음의 예를 봅시다.
상수 인스턴스가 아닌 상수 인터페이스 인 것 같습니다.

2021-01-03 15:04 UTC, merged