Item 18. 상속보다는 컴포지션을 사용하라
TheSwiftists/effective-swift pull request #53
Opened 2020-12-04 21:17 UTC by seizze

상속을 사용하여 기능을 확장할 때의 문제점과 그 대안인 컴포지션 대해 작성하였습니다.
또한, 스위프트에서 컴포지션이 사용된 예시에 대해 설명하였습니다.
추가적으로 상속을 이용한 기능 확장과, 스위프트에서 자주 사용하는 기능 확장 방법인 extension에 대해 저자가 설명한 내용 관점에서 비교해 보았습니다.

Closes #20

2020-12-08 06:35 UTC, Limwin94 approved these changes
컴포지션과 포워딩에 대해서 배워갑니다. 👍🏻

2020-12-08 06:35 UTC, Limwin94 commented on 4장_클래스와_인터페이스/item18.md
> +이런 오동작을 막기 위해 메서드 재정의를 피하고 새로운 메서드만 추가하는 방식으로 상속하더라도, 운 나쁘게 다음 릴리즈에서 상위 클래스에 같은 시그니처의 메서드가 생긴다면 재정의한 꼴이 되며 리턴 타입만 다르다면 컴파일 에러가 납니다.
릴리즈나 릴리스 한쪽으로 통일해주는게 매끄러워 보입니다!

2020-12-14 14:54 UTC, delmaSong approved these changes
수고하셨습니다! RxSwift의 예시를 보니 컴포지션에 대해 이해하기 수월했습니다 ㅎㅎ
가능하다면 왜 어떨때 상속보다는 컴포지션을 쓰는 게 더 좋을지에 대한 내용이 보충된다면 좋겠습니다 
물론 지금도 좋습니다 👍🏼

아 그리고 부제가 추가되어야 합니다!

2020-12-14 14:54 UTC, delmaSong commented on 4장_클래스와_인터페이스/item18.md
> +
`전달 방식` 뒤에 (forwarding) 이라고 붙여주면 좀 더 매끄럽게 이해할 수 있을 것 같습니다

2020-12-14 14:54 UTC, delmaSong commented on 4장_클래스와_인터페이스/item18.md
> +public class ForwardingSet<E> implements Set<E> {
책에 `18-2 래퍼 클래스 - 상속 대신 컴포지션 사용` 이라고 있는 것처럼 주석으로 각 클래스에 대해 간단하게 덧붙여주시면 스윞에 더 익숙한 사람이 어렵지 않게 볼 수 있을 것 같아요 ㅎㅎ

2020-12-15 16:58 UTC, seizze commented on 4장_클래스와_인터페이스/item18.md
> +이런 오동작을 막기 위해 메서드 재정의를 피하고 새로운 메서드만 추가하는 방식으로 상속하더라도, 운 나쁘게 다음 릴리즈에서 상위 클래스에 같은 시그니처의 메서드가 생긴다면 재정의한 꼴이 되며 리턴 타입만 다르다면 컴파일 에러가 납니다.
릴리즈로 통일했습니다. 감사합니다 👍

2020-12-15 16:59 UTC, seizze commented on 4장_클래스와_인터페이스/item18.md
> +
위에서는 계속 forwarding이라고 하다가 전달이라고 해서 읽는 사람이 혼란이 올 수 있겠네요~
추가했습니다. 감사합니다 👍

2020-12-15 17:03 UTC, seizze commented on 4장_클래스와_인터페이스/item18.md
> +
음 근데 보니까 섹션 타이틀도 포워딩이라고 적었고 전달이라는 말이 여기서만 나와서 여기만 전달이라고 쓰기도 좀 애매하네요..
포워딩으로 통일하겠습니다 ㅎㅎ 전달로 번역하는 것도 약간 의미가 어긋난다고 생각이 들어서요!

2020-12-15 17:07 UTC, seizze commented on 4장_클래스와_인터페이스/item18.md
> +public class ForwardingSet<E> implements Set<E> {
좋은 것 같아요! InstrumentedSet과 ForwardingSet에 각각 주석 추가했습니다.

2020-12-15 17:28 UTC, seizze commented
@delmaSong
책에서는 상속은 반드시 `하위 클래스 is-a 상위 클래스` 관계가 성립될 때, 확장하려는 클래스의 결함이 고려되었을 때, 그리고 아이템 19에 따르면 상위 클래스가 상속을 고려해 설계되고 문서화되었을 때 사용하라고 합니다. 그리고 아이템 10에서 나타났던 오버라이딩 문제같은 것들도 고려해야 하고..

제가 느끼기엔 상속을 쓰면서 견고한 코드를 작성하려면 굉장히 까다로우니 일단 상속을 최대한 피하고 컴포지션 또는 다른 방법들을 고려해 보라는 것 같아요. 그치만 이 의견은 너무 제 뇌피셜이고 근거가 부족해서 문서에 추가하기엔 적절하지 않은 것 같아서 하지 않으려 합니당..ㅎㅎ

부제는 이번 아이템의 내용의 원본 아이템 제목과 잘 맞는것 같아서 추가하지 않으려고 하는데 어떻게 생각하시나요??

2021-01-06 15:52 UTC, dev-Lena approved these changes
컴포지션과 포워딩에 대해 처음 알게됐는데 예시를 통해 설명해주셔서 감사합니다.
고생하셨습니다! 👍🏻✨

2021-01-08 16:55 UTC, ehgud0670 requested changes
꼼꼼히 보고 피드백 남겨봅니다~
컴포지션 내용을 새로 배웠고 RxSwift의 Subject와 Relay로 적절한 예시까지 
들여주셔서 매우 잘 읽었습니다. 
감사합니다!! (늦게 읽어 죄송합니다..ㅜ)

2021-01-08 16:55 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item18.md
> +
```suggestion
public InstrumentedSet(Set<E> s) {
        super(s);
}
```
=> 책처럼 생성자 추가 부탁드립니다~ 
이 부분이 없으면 컴파일에러가 나서요!!

2021-01-08 16:55 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item18.md
> +
이 부분이 읽히지가 않았는데, 읽어보니 책의 코드 18-1 내용이 있어야만 이해가능한 부분인 것 같습니다.
원활한 이해를 위해 코드 18-1 예제도 추가 설명해주시거나  **`addAll()`에서 `add()`를 호출하지 않고** 이 부분은 책의 코드 18-1의 HashSet 을 상속한 경우임을 알 수 있도록 추가 설명 부탁드립니다!

2021-01-08 16:55 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item18.md
> +만약 여기서 컴포지션이 아니라 상속과 오버라이드를 사용하였다면, 여러 문제가 발생합니다. 먼저 PublishSubject의 메서드들이 이미 public이기 때문에 클라이언트에서의 onError, onCompletion 호출을 완전히 막을 수는 없게 됩니다. 이 메서드들은 사용자를 혼란스럽게 할 수 있을 뿐더러, 상위 클래스의 메서드를 호출하여 하위 클래스
예시와 설명 모두 좋네요, 후덜덜👍👍👍

2021-01-08 16:55 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item18.md
> +스위프트에서는 객체의 기능 확장을 목적으로 extension을 사용합니다. 기능 확장에 extension을 사용할 때와 상속을 사용할 때를 비교해 보겠습니다.
* 저만 그런지 모르겠지만, 지금 이 문장만 읽으면 스위프트의 기능 확장으로 extension 만을 사용한다거나 주로 extension 을 사용한다고 느껴지는데 스위프트는 기능 확장으로 상속이나 extension 둘 다 사용하고 때에 따라 무엇을 써야 하는지 명시해주신다면 독자들에게 더 도움이 될 것 같습니다!
  * 첨언하자면, 아래 예제로 말씀하신 것처럼 extension는 기존 객체의 기능 확장이므로 오버라이드를 사용하지 않고, 따라서 오동작이 나지 않습니다. 즉, item18은 SRP를 구분지으며 확장하기 위해 상속 및 컴포지션을 쓰지만 스위프트의 extension는 기존 객체의 기능 확장이 목적이기 때문에 결이 조금 다른 것 같습니당. 이렇게 SRP 관점으로도 extension의 기능 확장의 의미가 상속과 어떻게 다른지 추가 설명 부탁드립니다 😊
  
https://stackoverflow.com/a/38827998/11612129 => 이렇게 상속과 extension 을 비교한 글을 보니 내용이 괜찮다 싶어서 피드백 드립니다.

2021-01-08 16:55 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item18.md
> +반면 상속과 마찬가지로, 운 나쁘게 다음 릴리즈에서 원본 객체에 같은 시그니처의 메서드가 생긴다면 extension의 수정이 필요합니다.
원본 객체에 같은 시그니처의 메서드가 생긴다면 자바는 런타임에 오동작하지만, 스위프트의 extension는 `Invalid redeclaration` 컴파일 에러를 일으키기 때문에 extension의 수정이 필요합니다.  `extension 의 수정이 왜 필요한지`가 상속과 다르므로, 이 부분만 추가 설명 부탁드립니다! 😃

2021-01-11 11:27 UTC, seizze commented on 4장_클래스와_인터페이스/item18.md
> +스위프트에서는 객체의 기능 확장을 목적으로 extension을 사용합니다. 기능 확장에 extension을 사용할 때와 상속을 사용할 때를 비교해 보겠습니다.
"SRP 관점에서 extension을 이용한 기능 확장의 의미"가 뭘 말하는지 잘 모르겠는데.. 더 설명해주실 수 있나여?

2021-01-11 11:41 UTC, seizze commented on 4장_클래스와_인터페이스/item18.md
> +
코드가 최대한 컴팩트하고 중요 부분만 있어야 읽기 편하다고 생각해서 아래 `// ...`로 코드가 더 있다고 명시했습니다! addAll도 생략했고 ForwardingSet도 많이 생략했어요~

2021-01-11 12:15 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item18.md
> +스위프트에서는 객체의 기능 확장을 목적으로 extension을 사용합니다. 기능 확장에 extension을 사용할 때와 상속을 사용할 때를 비교해 보겠습니다.
음 그러니깐, 스위프트의 extension은 기존 클래스의 기능 확장이라서 여기 item18의 예제 코드로 예를 들면 Set<E>에서 기능 확장을 한 것 과 같습니다. 그래서 자바의 컴포지션을 이용한 InstrumentedSet은 새로 책임을 지는 클래스인 반면 스위프트의 extension을 통한 기능 확장은 기존에 책임을 지는 클래스의 기능 확장이라 의미가 조금 다른 것 같아서여.

그래서 제 생각에는 자바의 포워딩/컴포지션 방식을 통한 기능 확장은 스위프트에서도 적용가능하지만(RxRelay로 예시를 들으신 것처럼), 이와는 성격이 다르지만 extension이란 것도 있고, **extension은 기존 상속/포워딩/컴포지션을 통한 기능 확장 말고 다른 상황(ex.임포트한 라이브러리의 객체에 기능 추가)에서 활용될 수 있다는 식**으로 비교되게 설명이 되면 좋을 것 같아서 코멘트 드렸습니다.

(그냥 SRP 내용은 굳이 언급안하고, 상속을 통한 기능 확장과 extension을 통한 기능 확장은 서로 다른 상황에서 쓰인다는 식으로 비교가 되면 좋을 것 같습니다. 제가 생각하기에는 item18의 예제와 extension을 통한 기능 확장은 서로 대응되지 않는 것 같아서여.. 🧐 하지만 extension은 매우 강력해서! item18 내용에 추가되었으면 합니다!)

2021-01-11 12:26 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item18.md
> +스위프트에서는 객체의 기능 확장을 목적으로 extension을 사용합니다. 기능 확장에 extension을 사용할 때와 상속을 사용할 때를 비교해 보겠습니다.
```suggestion
스위프트에서는 객체의 기능 확장을 목적으로 상속 말고도 extension을 사용합니다. 기능 확장에 extension을 사용할 때와 상속을 사용할 때를 비교해 보겠습니다.
```
=> 제가 뇌가 1차원적이라서(ㅠㅠ) 이해를 잘 못하는 것일 수도 있지만 요렇게 `상속 말고도` 같은 단어 추가되었으면 합니다.
뒤에 문장으로 상속과 비교한다고 해서 스위프트도 상속으로도 기능 확장을 하는구나라고 추론할 수 있지만, 명시적이면 더 전달이 잘 될 것 같아서요!! 😀

2021-01-11 12:30 UTC, seizze commented on 4장_클래스와_인터페이스/item18.md
> +스위프트에서는 객체의 기능 확장을 목적으로 extension을 사용합니다. 기능 확장에 extension을 사용할 때와 상속을 사용할 때를 비교해 보겠습니다.
네네 저도 다시 보니까 그렇게 쓰여진거 같아서 그부분은 고쳤어요 ㅎㅎ 피드백 감사합니다. SRP 때문에 보는중이었네요

2021-01-11 12:34 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item18.md
> +스위프트에서는 객체의 기능 확장을 목적으로 extension을 사용합니다. 기능 확장에 extension을 사용할 때와 상속을 사용할 때를 비교해 보겠습니다.
오 넵 ㅎㅎ 굿굿이네요

2021-01-11 12:47 UTC, seizze commented on 4장_클래스와_인터페이스/item18.md
> +스위프트에서는 객체의 기능 확장을 목적으로 extension을 사용합니다. 기능 확장에 extension을 사용할 때와 상속을 사용할 때를 비교해 보겠습니다.
제가 잘 이해한건지 모르겠는데, SRP 관점에서 봤을 때 상속을 통한 기능 확장과 extension을 통한 기능 확장이 상속은 다른 객체가 역할을 수행, 확장은 같은 객체가 역할을 수행하는 것이기 때문에 결이 다르다는거죠?? 그래서 글의 흐름이 잘 이어지지 않는다는 말이군요
근데 SRP 내용까지 포함하기엔.. 제가 명확하게 공부하지 않아서 맞는 내용을 쓸지 모르겠네요 ㅜㅜ

> 스위프트의 기능 확장으로 extension 만을 사용한다거나 주로 extension 을 사용한다고 느껴지는데 
이 부분은 다시보니 저도 그렇게 느껴져서 수정했습니다!

2021-01-11 12:53 UTC, seizze commented on 4장_클래스와_인터페이스/item18.md
> +반면 상속과 마찬가지로, 운 나쁘게 다음 릴리즈에서 원본 객체에 같은 시그니처의 메서드가 생긴다면 extension의 수정이 필요합니다.
그러네요! 수정이 필요한 원인이 다르네요
설명 추가했습니다~ :D

2021-01-11 13:10 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item18.md
> +스위프트에서는 객체의 기능 확장을 목적으로 extension을 사용합니다. 기능 확장에 extension을 사용할 때와 상속을 사용할 때를 비교해 보겠습니다.
넵, 솔직히 SRP 까지는 좀 그렇습니다. 그럼 상속과 달리 확장(Extension)는 `새로운 메소드와 연산 프로퍼티만` 추가 가능하다는 설명 추가하는거 제안드립니다. 그래야 좀 더 상속과 비교가 될 것 같아서여

* 확장(Extending): **오직 새로운 메소드와 연산 프로퍼티만** 추가 가능합니다. 하지만 코드에 새 클래스를 추가하지 않고도 어디서나 새 기능을 사용할 수 있습니다.

* 상속(Subclassing): **새 변수를 추가하고 함수를 재정의**할 수 있지만, 프로젝트 전체에서 특정 하위 클래스를 사용해야합니다.

=> 이거는 https://stackoverflow.com/a/38827998/11612129 여기 있는거 번역했습니다. 참고하시라고 적었습니다!

2021-01-11 13:10 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item18.md
> +반면 상속과 마찬가지로, 운 나쁘게 다음 릴리즈에서 원본 객체에 같은 시그니처의 메서드가 생긴다면 extension의 수정이 필요합니다.
넵, 감사합니다! :)

2021-01-11 13:59 UTC, seizze commented on 4장_클래스와_인터페이스/item18.md
> +스위프트에서는 객체의 기능 확장을 목적으로 extension을 사용합니다. 기능 확장에 extension을 사용할 때와 상속을 사용할 때를 비교해 보겠습니다.
확장에 대한 설명 추가했고, 앞 주제와 잘 이어지도록 표현 수정했습니다.

2021-01-11 14:03 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item18.md
> +스위프트에서는 객체의 기능 확장을 목적으로 extension을 사용합니다. 기능 확장에 extension을 사용할 때와 상속을 사용할 때를 비교해 보겠습니다.
넵!! 👍 👍 👍

2021-01-11 15:10 UTC, seizze commented on 4장_클래스와_인터페이스/item18.md
> +
말씀하신 예제 18-1과 self-use에 관한 구체적인 내용 추가했습니당~

2021-01-11 15:51 UTC, ehgud0670 approved these changes
정말 수고하셨습니다!! 너무 늦게 피드백 드렸는데 모두 반영해주시고 정말 감사합니다! ㅜㅜ
좋은 글 정말 잘 읽었습니다. 👏

2021-01-11 15:51 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item18.md
> +가장 큰 차이점으로는, 오버라이드를 사용하지 않기 때문에 이로 인한 오동작은 나타나지 않습니다. 내부적으로 자기 사용을 하더라도, 오버라이드된 메서드가 아닌 원본 메서드가 호출됩니다.
네네 거의 완벽합니다!! 고생하셨습니다. 👏
,,,

아래의 제안만 봐주세요, 아래 글을 제가 잘못 이해하고 추가한 것일 수도 있습니다.
제가 이해한 바로는 위 예제의 경우 Array의 extension으로 추가한 take 메소드를 다른 어느 곳에서 호출을 하더라도 오버라이드를 사용하지 않기 때문에 원본 메소드 take를 호출한다고 이해했습니다! 

그래서 제가 심심해서 extension의 메소드를 상속해서 오버라이드 시도해보니 non-objc 메소드면 오버라이드 안된다고 하네요
그래서 아래처럼 내용 추가 제안하는데 불필요하다고 생각하면 안 넣으셔도 됩니다.
```suggestion
가장 큰 차이점으로는, 오버라이드를 사용하지 않기 때문에 이로 인한 오동작은 나타나지 않습니다. 내부적으로 자기 사용을 하더라도, 오버라이드된 메서드가 아닌 원본 메서드가 호출됩니다(심지어 extension으로 추가한 메소드는 오버라이딩할 수 없습니다. 오버라이딩하는 경우 `Overriding non-@objc declarations from extensions is not supported` 컴파일 에러가 발생합니다).
```

2021-01-11 16:09 UTC, seizze commented on 4장_클래스와_인터페이스/item18.md
> +가장 큰 차이점으로는, 오버라이드를 사용하지 않기 때문에 이로 인한 오동작은 나타나지 않습니다. 내부적으로 자기 사용을 하더라도, 오버라이드된 메서드가 아닌 원본 메서드가 호출됩니다.
> Array의 extension으로 추가한 take 메소드를 다른 어느 곳에서 호출을 하더라도 오버라이드를 사용하지 않기 때문에 원본 메소드 take를 호출

네네 오버라이드를 사용하지 않기 때문에 원본 메서드가 호출된다는 것은 맞는데, take 보다는 기존 Array의 메서드들을 오버라이드하는 방식이 아니라서 기존 Array 원본 메서드가 호출된다는 의미였습니다 ㅎㅎ

> extension의 메소드를 상속해서 오버라이드 시도

기존 객체에 extension으로 기능추가할 때 오버라이드 문제가 발생하지 않는다는거랑, extension으로 추가 후에 또 그것을 상속하는건 또다른 내용인 것 같아서 넘어가도록 하겠습니다 :D

꼼꼼한 피드백 감사합니다~

2021-01-11 16:14 UTC, ehgud0670 commented on 4장_클래스와_인터페이스/item18.md
> +가장 큰 차이점으로는, 오버라이드를 사용하지 않기 때문에 이로 인한 오동작은 나타나지 않습니다. 내부적으로 자기 사용을 하더라도, 오버라이드된 메서드가 아닌 원본 메서드가 호출됩니다.
아하 이해 잘됐습니다 :) ㅎㅎ
그리고 너무 피드백해서 탈이었을텐데ㅋㅋ  다 대답해주셔서 감사합니다 👍 
넵 그럼 머지 하셔도 됩니다~ 😃

2021-01-11 16:16 UTC, seizze commented on 4장_클래스와_인터페이스/item18.md
> +가장 큰 차이점으로는, 오버라이드를 사용하지 않기 때문에 이로 인한 오동작은 나타나지 않습니다. 내부적으로 자기 사용을 하더라도, 오버라이드된 메서드가 아닌 원본 메서드가 호출됩니다.
ㅋㅋㅋㅋㅋ
아니에요 저도 도움이 많이 됐습니다! 미비했던 부분도 많이 보충된것 같아요 ㅎㅎ 👍👍

2021-01-11 16:16 UTC, merged