아이템별 담당자 및 파일 링크 추가(12월 7일) + 리드미 목차 테이블에 서브 타이틀 열(Column) 추가
TheSwiftists/effective-swift pull request #59
Opened 2020-12-07 08:54 UTC by dev-Lena

### 추가한 내용

1. 아이템 29 ~ 35 담당자 및 파일 링크를 추가했습니다.
2. 리드미 목차 테이블에 서브 타이틀 열(Column)을 추가했습니다.

## 참고
- 현재 오픈되어있는 #52 docs 브랜치에서 branch를 따 만들었습니다.
- 예시 각 폴더에 남아있는 md파일인 item0.md 삭제는 추후에 하도록 하겠습니다.

2020-12-14 14:07 UTC, delmaSong approved these changes
수고하셨습니다 👍🏼

2020-12-14 14:13 UTC, ehgud0670 approved these changes
확인했습니다. 수고하셨습니다. 👍

2020-12-14 14:47 UTC, seizze commented on README.md
> +|  아이템 9   | [try-finally보다는 try-with-resources를 사용하라](2장_객체_생성과_파괴/item9.md) |             | [Lin](https://github.com/Limwin94)    |
공백이랑 dash는 원래대로 해주셨으면 좋겠어요. 제 에디터에서는 이렇게 돼버려서 보기가 힘드네여..
![image](https://user-images.githubusercontent.com/49332230/102095073-6f4f8200-3e66-11eb-802d-e2c03df39b66.png)

2020-12-14 14:48 UTC, seizze requested changes
수고하셨음다.👍

2020-12-24 11:21 UTC, Limwin94 approved these changes
고생하셨습니다

이제 서브타이틀 고민하느라 새치올라올거같아요..

2020-12-24 11:21 UTC, dev-Lena commented on README.md
> +|  아이템 9   | [try-finally보다는 try-with-resources를 사용하라](2장_객체_생성과_파괴/item9.md) |             | [Lin](https://github.com/Limwin94)    |
앗 네! 공백이랑 dash 기존 문서에서 가져와 수정해봤습니다. -> 71291ab
이렇게 하면 잘 보이시나요?

2020-12-27 11:37 UTC, seizze approved these changes
ㅎㅎ 고생하셨습니다 😣

2020-12-28 12:36 UTC, merged