Item3. private 생성자나 열거 타입으로 싱글턴임을 보증하라
TheSwiftists/effective-swift pull request #6
Opened 2020-10-20 14:11 UTC by idevjinie

- 책에서 제시하는 자바의 싱글턴 생성 방식과 스위프트의 방식을 비교하여 설명했습니다.
- 싱글턴의 장단을 소개하고 해결방안을 기재했습니다.
- 문서에 포함된 이미지 파일은 문서가 위치한 경로에 `resources` 폴더를 두어 추가했습니다.

2020-10-20 15:57 UTC, seizze requested changes
글로만 전달받다보니 의도치 않게 이해가 가지 않는 부분이 생긴 것 같아요 😢
귀찮더라도 조금만 수정 부탁드려용

마지막으로, 이미지 출처라던지 참고한 링크 추가해 주시면 여한이 없을듯,,

2020-10-20 15:57 UTC, seizze commented on README.md
> +| 아이템 3 | [private 생성자나 열거 타입으로 싱글턴임을 보증하라]() | [jinie](https://github.com/idevjinie) |
여기 item3 페이지로 가는 링크도 추가 부탁드림당.
괄호 안에 `chapter2/item3.md` 라고만 써주시면 돼용

2020-10-20 15:57 UTC, seizze commented on chapter2/item3.md
> +용이한 테스트를 위해 싱글턴으로 접근하지 않고, 생성자에 의존성을 주입한다. 여기서 의존성이란 서비스로 사용할 수 있는 객체이고, 주입은 의존성(서비스)을 사용하려는 객체로 전달하는 것을 의미한다. 즉, 객체가 어떤 서비스를 사용할 것인지 지정하는 대신, 객체에게 어떤 서비스를 사용할 것인지를 말해주는 것이다.
싱글턴에 의존하는 코드를 테스트하기 어렵기 때문에 의존성 주입을 이용한다는 흐름인거죠?? 그런 말을 조금만 더 추가해 주시면 이해가 더 잘 갈것 같아요~

2020-10-20 15:57 UTC, seizze commented on chapter2/item3.md
> +아래의 싱글턴 예시를 보면 `UserManager`의 `currentUser`가 옵셔널로 정의되어 있는 것을 확인할 수 있다. 뷰 컨트롤러가 표시되는 시점에 데이터가 실제로 존재한다는 컴파일 타임 보장이 없기 때문이다.
사실 이 부분이 이해가 잘 안가요 ㅠㅠ흑흑 UserManager와 currentUser의 코드라던지 관련 정보가 더 있었으면 좋겠어요

2020-10-21 01:19 UTC, delmaSong requested changes
저도 하이디랑 의견이 같습니다~ `UserManager`와 `LogoutService`에 대한 코드만 보충해주시면 좋을 것 같아요. 그 외에는 싱글턴의 장단점을 잘 정리해주셨네요 👍🏻

2020-10-21 01:23 UTC, Limwin94 requested changes
싱글톤에 대한 장단점, 열거형으로 싱글톤구조를 만들면 안되는 이유에 대해 잘 설명해주셔서 감사합니다.
하이디가 말한 부분만 내용추가하시면 깔끔할것 같습니다~!

2020-10-21 01:23 UTC, Limwin94 commented on chapter2/item3.md
> +아래의 싱글턴 예시를 보면 `UserManager`의 `currentUser`가 옵셔널로 정의되어 있는 것을 확인할 수 있다. 뷰 컨트롤러가 표시되는 시점에 데이터가 실제로 존재한다는 컴파일 타임 보장이 없기 때문이다.
왜 보장할 수 없을까요.. @seizze 말대로 조금 더 정보가 있으면 좋겠습니다.

2020-10-21 04:21 UTC, dev-Lena reviewed
싱글턴에 대해 설명해주셔서 감사합니다!!

2020-10-21 04:21 UTC, dev-Lena commented on chapter2/item3.md
> +책에서 자바를 사용한 싱글턴 생성 방식으로 `private` 생성자와 열거 타입을 소개하는데, 스위프트는 `private` 생성자를 사용하는 방식을 취한다. 스위프트의 열거 타입은 값 타입(value type)으로, 앱 전체에서 공유하여 사용하는 싱글턴의 용도에 부합하지 않고, 열거 타입 내부에 원시값으로 싱글턴 인스턴스를 갖는다면 외부에서 생성이 가능한
스위프트에서 `private` 생성자를 사용하는 방식에 대한 예가 있어도 좋을 것 같습니다!

2020-10-21 04:21 UTC, dev-Lena commented on chapter2/item3.md
> +싱글턴은 Apple 자체에서도 많이 사용하는 만큼 편리하다는 장점이 있다. 어디에서나 접근이 가능하고 앱 전체에서 공유될 수 있다. 그러나 멀티 스레드 환경에서 동시에 참조한다거나, 객체 간의 명확한 분리 없이 광범위하게 사용할 경우 원치 않은 결과와 버그가 발생할 수 있다. 따라서 객체 간에 보다 잘 정의된 관계를 만들고, 의존성 주입을 사용하는 등 주
결론 부분에 item3 책 내용(스위프트에서 싱글턴임을 보장하는 방법)이 더해지면 더 좋을 것 같아요!

2020-10-23 00:00 UTC, Limwin94 commented on chapter2/item3.md
> +싱글턴은 Apple 자체에서도 많이 사용하는 만큼 편리하다는 장점이 있다. 어디에서나 접근이 가능하고 앱 전체에서 공유될 수 있다. 그러나 멀티 스레드 환경에서 동시에 참조한다거나, 객체 간의 명확한 분리 없이 광범위하게 사용할 경우 원치 않은 결과와 버그가 발생할 수 있다. 따라서 객체 간에 보다 잘 정의된 관계를 만들고, 의존성 주입을 사용하는 등 주
> 결론 부분에 item3 책 내용(스위프트에서 싱글턴임을 보장하는 방법)이 더해지면 더 좋을 것 같아요!

위에 예제가 있어 중복될 수도 있을 것 같습니다.

```swift
class Singleton {
    static let shared = Singleton()
    private init() { }
}
```

2020-10-25 10:18 UTC, delmaSong approved these changes

2020-10-25 10:20 UTC, idevjinie commented
피드백 반영했습니다. 기존의 예시를 이해하는 데 어려움이 있는 듯해 코드와 설명을 추가했습니다. 확인 부탁드립니다~

2020-10-25 11:10 UTC, seizze approved these changes
싱글턴 인스턴스 UserManager의 생명주기가 User의 생명주기보다 길어서 user 프로퍼티가 옵셔널인것이었군요. 이해가 잘 됩니다! 수고하셨습니다~

2020-10-27 01:14 UTC, Limwin94 approved these changes
고생하셨습니다!

2020-10-27 03:56 UTC, merged