item 32. 제네릭과 가변인수(varargs)를 함께 쓸 때는 신중하라
TheSwiftists/effective-swift pull request #61
Opened 2020-12-18 19:20 UTC by ehgud0670

### item 32. 제네릭과 가변인수(varargs)를 함께 쓸 때는 신중하라

2020-12-26 13:49 UTC, dev-Lena requested changes
알찬 내용 감사합니다 덕분에 많이 공부가 됐습니다 👍 

질문과 제안사항을 코멘트로 달았습니다!
그리고 마지막에 참고한 자료도 함께 남겨주시면 좋을것 같습니다 :)

수고하셨습니다! 🐝

2020-12-26 13:49 UTC, dev-Lena commented on 5장_제네릭/item32.md
> +얖서 item32 에서는 제네릭과 배열은 함께 사용할 수 없다는 것(컴파일 오류)을 배웠습니다.
```suggestion
앞서 item28 에서는 제네릭과 배열은 함께 사용할 수 없다는 것(컴파일 오류)을 배웠습니다.
```
오타가 있는 것 같습니다!

2020-12-26 13:49 UTC, dev-Lena commented on 5장_제네릭/item32.md
> +* 애초에, Swift에서 가변인수 및 배열은 Value 타입이라 다른 값을 저장함으로써 발생하는 문제가 생기지 않습니다.
Value 타입(값 타입)이라고 명시하면 더 좋을 것 같습니다!

2020-12-26 13:49 UTC, dev-Lena commented on 5장_제네릭/item32.md
> +* 제네릭과 배열을 함께 사용하면 불공변(invariant)인 제네릭의 특징이 배열로 인해 덮어지고, 타입이 불안정해져서 런타임 에러 가능성이 생깁니다.
개인적인 의견인데요! 이전 내용을 되짚어 보면서 Java에서 제네릭과 배열의 타입 체크 시점이 다르다는(제네릭 - 컴파일 타임, 배열 - 런타임) 내용도 있으면 더 좋을 것 같습니다.

2020-12-26 13:49 UTC, dev-Lena commented on 5장_제네릭/item32.md
> +=> 따라서 위 메서드는 아무 문제가 없는 메서드이니 별다른 경고 없이 컴파일 되지만, 결국 pickTwo의 반홥타입이 Object[]라 String[] 으로 자동 형변환되어 ClassCastException 이 발생합니다. 정리하지면 제네릭 varargs(T...) 매개변수를 그대로 반환하고 또 제네릭을 이용해 반환하는 메서드(pickTow)로 인해 C
`반홥타입` -> `반환타입` 오타가 있네요 :)

제네릭 메서드에서 제네릭 배열을 리턴할 경우 컴파일 시에 리턴타입이 Object[]으로 정해지는건지 궁금합니다.

2020-12-26 13:49 UTC, dev-Lena commented on 5장_제네릭/item32.md
> +=> pickTwo 메서드는 내부에서 toArray 메서드를 호출합니다. 이 메서드가 toArray()에 넘길 배열의 타입은 Object[]인데 pickTwo에 어떤 타입의 객체를 넘기더라도 담을 수 있는 구체적인 타입이기 때문입니다.
현재 toArray()에 넘기는 타입(a,b,c)은 T(제네릭)타입인거 아닌가요?

2020-12-26 13:49 UTC, dev-Lena commented on 5장_제네릭/item32.md
> +=> 위 코드에서 stringLists를 objects 변수에 할당할 때부터 둘은 같은 객체를 바라보는게 아니라 복사가 되는 것이기 때문에 이후에 intList 값을 저장해서 일어나는 문제가 발생하지 않습니다.
`둘은 같은 객체를 바라본다`는 표현보다 같은 `객체의 주소값을 가리킨다`는 표현을 제안해봅니다!

2020-12-26 14:24 UTC, ehgud0670 commented on 5장_제네릭/item32.md
> +=> 따라서 위 메서드는 아무 문제가 없는 메서드이니 별다른 경고 없이 컴파일 되지만, 결국 pickTwo의 반홥타입이 Object[]라 String[] 으로 자동 형변환되어 ClassCastException 이 발생합니다. 정리하지면 제네릭 varargs(T...) 매개변수를 그대로 반환하고 또 제네릭을 이용해 반환하는 메서드(pickTow)로 인해 C
이건 스터디때도 말씀드렸던 것처럼 pickTwo에서 toArray에 제네릭 타입 T인 인자를 넘겨줌으로써 toArray가 결국 반환할 타입이 Object[]가 된다는 것입니다.
만약 toArray에 String 값이 넘어가면 반환값이 String 으로 확실해지지만, 위의 예제처럼 제네릭 T 타입를 넘긴 경우 T가 어떤 타입이어도 대응해야 하기 때문에 Object[]가 반환된다는 것입니다. 

그래서 제네릭 + 가변인자를 사용하는 경우에는 (이런 특수한 경우라도) ClassCastException이 발생할 수 있기 때문에 사용할 때 조심하자는 것입니다. 질문 감사합니다 :)

2020-12-26 15:03 UTC, ehgud0670 commented on 5장_제네릭/item32.md
> +* 제네릭과 배열을 함께 사용하면 불공변(invariant)인 제네릭의 특징이 배열로 인해 덮어지고, 타입이 불안정해져서 런타임 에러 가능성이 생깁니다.
자바에서 제네릭과 배열의 타입 체크는 모두 컴파일 시점에 체크가 되지만, 
배열은 공변이라 타입이 불안정하고 제네릭은 불공변이라 타입 안정(safe)합니다. 
피드백을 반영하여 배열은 공변, 제네릭은 불공변인 특징을 추가 설명하였습니다.
감사합니다 :)

2020-12-26 15:06 UTC, ehgud0670 commented on 5장_제네릭/item32.md
> +* 애초에, Swift에서 가변인수 및 배열은 Value 타입이라 다른 값을 저장함으로써 발생하는 문제가 생기지 않습니다.
네 반영하였습니다!

2020-12-26 15:08 UTC, ehgud0670 commented on 5장_제네릭/item32.md
> +=> 위 코드에서 stringLists를 objects 변수에 할당할 때부터 둘은 같은 객체를 바라보는게 아니라 복사가 되는 것이기 때문에 이후에 intList 값을 저장해서 일어나는 문제가 발생하지 않습니다.
네! 수정하였습니다. 괄호안에 `같은 주소값` 을 추가했어요

2020-12-26 15:11 UTC, ehgud0670 commented on 5장_제네릭/item32.md
> +=> pickTwo 메서드는 내부에서 toArray 메서드를 호출합니다. 이 메서드가 toArray()에 넘길 배열의 타입은 Object[]인데 pickTwo에 어떤 타입의 객체를 넘기더라도 담을 수 있는 구체적인 타입이기 때문입니다.
위에 설명드린 것처럼 Object[] 가 반환됩니다. 피드백 반영하여 위의 설명을 추가했어요.
감사합니다 :)

2020-12-26 15:17 UTC, ehgud0670 commented
참고 링크는 Swift 가변 인수에 대한 내용 추가하면서 남기겠습니다~

2020-12-26 15:25 UTC, ehgud0670 commented on 5장_제네릭/item32.md
> +=> 따라서 위 메서드는 아무 문제가 없는 메서드이니 별다른 경고 없이 컴파일 되지만, 결국 pickTwo의 반홥타입이 Object[]라 String[] 으로 자동 형변환되어 ClassCastException 이 발생합니다. 정리하지면 제네릭 varargs(T...) 매개변수를 그대로 반환하고 또 제네릭을 이용해 반환하는 메서드(pickTow)로 인해 C
오타 수정하였습니다. 감사합니다

2020-12-27 06:53 UTC, gwonii approved these changes
고생하셨습니다. 스위프트를 쓰면서 가변인수를 거의 사용할 일이 없었는데 의미있는 챕터였던 것 같습니다.

2020-12-27 09:33 UTC, delmaSong approved these changes
역시 스위프트가 짱이네요.. 수고하셨습니다 🔥

2020-12-27 09:34 UTC, delmaSong commented on 5장_제네릭/item32.md
> +
오타만 수정했습니다
```suggestion
=> 따라서 위 메서드는 아무 문제가 없는 메서드이니 별다른 경고 없이 컴파일 되지만, 결국 pickTwo의 반환타입이 Object[]라 String[] 으로 자동 형변환되어 ClassCastException 이 발생합니다. 정리하지면 제네릭 varargs(T...) 매개변수를 그대로 반환하고 또 제네릭을 이용해 반환하는 메서드(pickTwo)로 인해 ClassCastException 이 발생한 것입니다. 

```

2020-12-27 09:34 UTC, ehgud0670 commented on 5장_제네릭/item32.md
> +
감사합니다 :)

2020-12-27 11:10 UTC, dev-Lena approved these changes
고생하셨습니다!👏🏻

2021-01-11 06:52 UTC, Limwin94 approved these changes
고생하셨습니다!

2021-01-11 10:40 UTC, merged