Item30. 이왕이면 제네릭 메서드로 만들라
TheSwiftists/effective-swift pull request #62
Opened 2020-12-18 19:39 UTC by Limwin94

Swift의 제네릭, 제네릭 메서드를 소개(설명)해보았습니다.

2020-12-19 14:07 UTC, seizze commented
리드미 수정은 레나가 다른 PR로 해서 안해도 될것 같아요~ 충돌날듯??

2020-12-19 14:21 UTC, delmaSong reviewed
제너릭을 사용했을 때의 이름 짓는 방법까지 아주 유용하게 읽었습니다~
아까 스터디때 이야기 나눴던대로 제너릭에 관해 조금 더 들어가서
프로토콜을 이용 할 때 제너릭을 쓰는 방법에 대해 보충이 되면 아주 좋겠어요 💥

리드미는 충돌을 방지하기 위해 레나의 PR이 머지된 이후에 수정하기로 해요!

2020-12-19 14:21 UTC, delmaSong commented on 5장_제네릭/item30.md
> +Java와 선언하는 방식이나 개념이 크게 다르지 않습니다.
`메소드`와 `메서드` 중 하나로 통일해주세요 ㅎㅎ
그리고 개요 부분에 제너릭 메서드의 어떠한 부분 때문에 제너릭 메서드로 만들어라~ 하는 부분이 좀 보충되면 좋겠습니당

2020-12-27 07:21 UTC, gwonii requested changes
좋은 내용 감사합니다.

2020-12-27 07:21 UTC, gwonii commented on 5장_제네릭/item30.md
> +
Swift에서는 제네릭 메서드를 만들 때 타입 한정을 통해 유연하게 제네릭 메서드를 만들 수 있는 것으로 알고 있습니다. 
책에서 자바같은 경우에는 재귀적 타입 한정만을 얘기하고 있는데 
이 부분에 대해서 내용이 추가되면 좋을 것 같습니다. 
제가 잘못알고 있는 부분이 있다면 피드백 부탁드리겠습니다!

2021-01-06 16:11 UTC, dev-Lena approved these changes
제네릭 메서드에 대한 자료 잘봤습니다! 지금도 좋지만 gwonii님 의견대로 타입 제약에 대한 내용이 추가적으로 들어가도 좋을것 같네요!

수고하셨습니다✨

2021-01-11 14:26 UTC, ehgud0670 approved these changes
좋은 내용 잘 읽었습니다.
내용이 매우 정리가 잘 되있네요 👍
수고하셨습니다!!

2021-01-11 14:26 UTC, ehgud0670 commented on 5장_제네릭/item30.md
> +
저도 호권이처럼 타입 한정을 통해 제네릭 파라미터나 리턴값이 제한시킬 수 있다는 내용만 추가되었으면 좋겠습니다 ㅎㅎ

2021-01-12 01:11 UTC, Limwin94 commented on 5장_제네릭/item30.md
> +Java와 선언하는 방식이나 개념이 크게 다르지 않습니다.
앗 알겠습니다. 메서드로 통일해볼게요~
개요 부분도 저녁에 수정토록 하겠습니다 :)

2021-01-17 07:38 UTC, Limwin94 commented on 5장_제네릭/item30.md
> +
짧게나마 추가해보았습니다. 혹시 여기서 더 추가적인 설명이 필요할 경우 코멘트 부탁드립니다!

2021-01-17 10:06 UTC, seizze requested changes
수고하셨습니다~~👏👏👏

2021-01-17 10:06 UTC, seizze commented on 5장_제네릭/item30.md
> +```
여기 중간에 ` ```Swift`가 한번더 들어갔네요~

2021-01-17 10:06 UTC, seizze commented on 5장_제네릭/item30.md
> +}
"T는 SomeClass를 상속하는 클래스"면 하위클래스로 읽혀집니다. 그냥 SomeClass의 상위클래스들이라고만 쓰면 될거 같아요~!

2021-01-17 13:08 UTC, gwonii approved these changes
고생많으셨습니다~

2021-01-17 13:59 UTC, Limwin94 commented on 5장_제네릭/item30.md
> +```
제거했습니다 :)

2021-01-17 14:00 UTC, Limwin94 commented on 5장_제네릭/item30.md
> +}
넵 헷갈릴 수 있는 표현 제거후 제안하신 내용대로 변경했습니다. 감사합니다.

2021-01-17 14:02 UTC, seizze approved these changes

2021-01-17 14:04 UTC, merged