Item35. ordinal 메서드 대신 인스턴스 필드를 사용하라
TheSwiftists/effective-swift pull request #63
Opened 2020-12-18 20:37 UTC by ehgud0670

### Item35. ordinal 메서드 대신 인스턴스 필드를 사용하라

인스턴스 필드 사용하세요!!

2020-12-20 08:31 UTC, delmaSong approved these changes
수고하셨습니다~!
스터디때 이야기 나눈 몇몇사항 보충해주시면 좋을 것 같아요 👍🏼

2020-12-20 08:31 UTC, delmaSong commented on 5장_제네릭/item35.md
> +
H3 사이즈로 변경하는 게 좋을 것 같아요 ㅎㅎ

2020-12-20 08:31 UTC, delmaSong commented on 5장_제네릭/item35.md
> +
여기랑 `올바른 쓰임새` 부분도 H3 사이즈면 전체 스타일에 통일성이 있을 것 같아요

2020-12-20 08:31 UTC, delmaSong commented on 5장_제네릭/item35.md
> +
어제 얘기 나눴던대로 개별적으로 명시적인 값을 갖게 함으로써 ordinal()을 사용해서 일어나는 문제는 해결될 것으로 보입니다~!

2020-12-20 09:47 UTC, ehgud0670 commented on 5장_제네릭/item35.md
> +
네, 그래서 시도해 보았더니 rawValue는 unique 해야 해서 OCTET(=8), DOUBLE_QUARTET(=8) 처럼 중복된 경우에 사용할 수 없었습니다. 따라서 rawValue 의 명시적 사용은 시도했던 것만 문서에 적겠습니다. 감사합니다. 😊

2020-12-20 10:24 UTC, ehgud0670 commented on 5장_제네릭/item35.md
> +
넵, 피드백을 반영하여 H3 사이즈로 변경하였습니다.

2020-12-20 10:24 UTC, ehgud0670 commented on 5장_제네릭/item35.md
> +
넵, 피드백을 반영하여 H3 사이즈로 변경하였습니다.

2020-12-27 11:07 UTC, seizze requested changes
아이템 35는 6장에 해당하니 6장 디렉토리로 이동해 주세요~!

2020-12-27 11:07 UTC, seizze commented on 5장_제네릭/item35.md
> +      System.out.println(iter.next());
들여쓰기 스페이스 4개로 통일 부탁드려요~

2020-12-27 11:07 UTC, seizze commented on 5장_제네릭/item35.md
> +        }
```swift
struct Choir: Equatable {
    enum Ensemble {
        case solo, duet, octet, doubleQuartet // ...
    }
    
    private init(_ ensumble: Ensemble, numberOfMusicians: Int) {
        self.ensumble = ensumble
        self.numberOfMusicians = numberOfMusicians
    }
    
    let ensumble: Ensemble
    let numberOfMusicians: Int
    
    static let solo = Choir(.solo, numberOfMusicians: 1)
    //...
    static let octet = Choir(.octet, numberOfMusicians: 8)
    static let doubleQuartet = Choir(.doubleQuartet, numberOfMusicians: 8)
}
```

책의 방법처럼 프로퍼티로 저장해 놓는 방식이 좋을 것 같아서 이런 방식 제안해 봅니당.

책의 인스턴스 필드의 경우와 같이 중간에 값을 비우거나 끼워 넣을 수 있고, `numberOfMusicians`의 중복이 가능합니다.
struct에 static let을 써서 열거형처럼 `.solo` 형태로 타입 추론도 가능하며, 내부적으로 열거형을 갖는 형태기 때문에 실제 열거형처럼 모든 case가 구분됩니다.

```swift
print(Choir.octet == Choir.doubleQuartet) // false
```

2020-12-27 11:07 UTC, seizze commented on 5장_제네릭/item35.md
> +        return AllCases().count
이렇게 하면 값이 나오지 않고, 실제 연산 프로퍼티인 `allCases`에 접근해야 모든 case가 들어있는 컬렉션을 만드는 걸로 알고 있는데 한번 확인 부탁드립니다~
```swift
allCases.count
```

2020-12-27 11:33 UTC, ehgud0670 commented on 5장_제네릭/item35.md
> +        return AllCases().count
맞습니다. associatedtype인 AllCases 말고, 실제 연산 프로퍼티인 allCase로 접근해야 모든 count가 제대로 나옵니다.
수정했습니다.
알려주셔서 감사합니다~

2020-12-27 11:34 UTC, ehgud0670 commented on 5장_제네릭/item35.md
> +      System.out.println(iter.next());
네 수정하였습니다 :)

2020-12-27 13:14 UTC, ehgud0670 commented on 5장_제네릭/item35.md
> +        }
좋은 제안 감사합니다 ㅎㅎ
struct를 같이 사용하면 좋네요 ㅋㅋ
이 내용 추가할테니 그 때도 봐주세요 👍

2020-12-28 03:18 UTC, seizze commented on 6장_열거_타입과_애너테이션/item35.md
> +* Swift의 switch는 **exhausive** 해서 default를 쓰지 않는한 값을 추가할 때 switch 컴파일 오류를 통해 case를 추가해야 함을 알 수 있습니다.
오타 exhausive > exhaustive t가 빠졌네여 ☺️

2020-12-28 03:21 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item35.md
> +* Swift의 switch는 **exhausive** 해서 default를 쓰지 않는한 값을 추가할 때 switch 컴파일 오류를 통해 case를 추가해야 함을 알 수 있습니다.
아 넴 ㅎㅎ 수정하겠습니다

2020-12-28 03:59 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item35.md
> +* Swift의 switch는 **exhausive** 해서 default를 쓰지 않는한 값을 추가할 때 switch 컴파일 오류를 통해 case를 추가해야 함을 알 수 있습니다.
반영하였습니다~

2021-01-06 16:18 UTC, dev-Lena approved these changes
자료 잘봤습니다 ☺️  고생하셨습니다 👍🏻

2021-01-17 13:24 UTC, gwonii approved these changes
알찬 정보 감사합니다~ 😀

2021-01-18 03:04 UTC, Limwin94 approved these changes
고생하셨습니다. 몇가지 부분만 확인 부탁드릴게요 :)

2021-01-18 03:04 UTC, Limwin94 commented on 6장_열거_타입과_애너테이션/item35.md
> +왜냐하면 rawValue는 unique 해야 되기 때문에 OCTET(= 8), DOUBLE_QUARTET(=8) 처럼 값이 중복이 되는 경우에는 rawValue를 사용할 수 없기 때문입니다.
`= 8` 혹은 `=8`로 통일 한번 부탁드릴게요.

2021-01-18 03:04 UTC, Limwin94 commented on 6장_열거_타입과_애너테이션/item35.md
> +=> 마지막 NumberOfTypes가 3이 되어 저절로 모든 case의 총 개수로 이용될 수 있습니다. 하지만 이 방법은 팀원들끼리 서로 알려줘야 하고, 이후 코드를 잘 못 건드릴 경우 총 개수로서 작동하지 않을 수 있는 위험이 있습니다.
팀원들끼리 NumberOfTypes가 무엇을 뜻하는지 공유해야한다는 의미인거죠?.?

2021-02-12 12:36 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item35.md
> +=> 마지막 NumberOfTypes가 3이 되어 저절로 모든 case의 총 개수로 이용될 수 있습니다. 하지만 이 방법은 팀원들끼리 서로 알려줘야 하고, 이후 코드를 잘 못 건드릴 경우 총 개수로서 작동하지 않을 수 있는 위험이 있습니다.
넵, `무엇을 뜻하는지 팀원들끼리 공유해야 하고`로 글 대체하였습니다. 감사합니다~ 👍

2021-02-12 12:36 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item35.md
> +왜냐하면 rawValue는 unique 해야 되기 때문에 OCTET(= 8), DOUBLE_QUARTET(=8) 처럼 값이 중복이 되는 경우에는 rawValue를 사용할 수 없기 때문입니다.
넵, 통일하였습니다!

2021-02-12 12:40 UTC, ehgud0670 commented on 5장_제네릭/item35.md
> +        }
드디어 반영했네요 ㅋㅋ 다만 저는 그냥 Ensemble 만 두고 싶어 struct `Ensemble`, enum `Kind`로 설명하였고 덧붙여 struct `Choir`, enum `Ensemble`도 좋은 이름이라고 추가하였습니다. 좋은 제안 정말  감사합니다 👍👍👍

2021-02-21 09:22 UTC, seizze reviewed
바깥 구조체는 Choir보다 Ensemble이 더 어울리는거 같네요!

2021-02-21 09:29 UTC, seizze approved these changes

2021-02-21 09:41 UTC, ehgud0670 commented
처음 제안하신 하이디가 왕따봉이죠 ㅎㅎ 감사합니다!

2021-02-21 14:57 UTC, merged