item29. 이왕이면 제네릭 타입으로 만들라
TheSwiftists/effective-swift pull request #64
Opened 2020-12-19 02:01 UTC by dev-Lena

Stack에 대한 Swift 예시를 작성했습니다.

2021-01-07 09:27 UTC, dev-Lena commented
### 스터디 이후 내용 추가
제네릭에 대한 아래의 내용을 추가했습니다 : ) 리뷰 부탁드립니다 🙌🏻

- 제네릭의 동작방식
- Stack 예시 (제네릭을 사용할 경우와 아닌 경우 비교)
- 타입 제약
- Any vs Generic
- 연관 타입 소개

2021-01-11 14:51 UTC, ehgud0670 approved these changes
컴파일러 동작부터 연관타입까지 내용이 굉장하네요.. 👏
이택릭체 적용한것만 수정 부탁드립니다.
덕분에 잘 읽었습니다. 감사합니다~~ 👍

2021-01-11 14:51 UTC, ehgud0670 commented on 5장_제네릭/item 29.  이왕이면 제네릭 초고(Generic 문서).md
> +컴파일러에는 이 함수를 위해 코드를 보내는데 필요한 두 가지 필수 정보인 1. _T타입 변수의 사이즈_와 2. _런타임에 호출해야하는_ `<` 메서드의 특정 오버로드 주소가 없습니다.
```suggestion
컴파일러에는 이 함수를 위해 코드를 보내는데 필요한 두 가지 필수 정보인 1. _T타입 변수의 사이즈_ 와 2. _런타임에 호출해야하는_ `<` 메서드의 특정 오버로드 주소가 없습니다.
```
이탤릭체 잘 적용되게 제안합니다~

2021-01-11 14:51 UTC, ehgud0670 commented on 5장_제네릭/item 29.  이왕이면 제네릭 초고(Generic 문서).md
> +  _뺄셈 연산자를 사용할 수 있는 타입_이어야 하기 때문에 매개변수를 BinaryInteger 프로토콜을 준수하는 타입으로 한정.
```suggestion
  _뺄셈 연산자를 사용할 수 있는 타입_ 이어야 하기 때문에 매개변수를 BinaryInteger 프로토콜을 준수하는 타입으로 한정.
```
이탤릭체 잘 적용되게 제안합니다~

2021-01-15 14:41 UTC, delmaSong approved these changes
스위프트의 제너릭에 대한 내용이 여기 전부 담겨있는 것 같네요! 정말 잘 읽었습니다 👍🏼

2021-01-15 14:41 UTC, delmaSong commented on 5장_제네릭/item 29.  이왕이면 제네릭 초고(Generic 문서).md
> +    mutating func append(_ item: Int) {
typealias 위치만 프로퍼티 윗부분으로 옮겨주실 수 있을까요?

2021-01-16 06:21 UTC, delmaSong commented
md파일 이름을 item29.md로 수정바랍니다!

2021-01-17 11:42 UTC, seizze requested changes
다양한 내용이 많네요! 수고하셨습니다.
델마 말대로 파일 이름만 변경해 주세요 :D

2021-01-17 12:59 UTC, gwonii approved these changes
Any와 AnyObject를 거의 써보질 않았는데, Generic이랑 비교를 직접 해보니 안쓰고 있었던 이유가 있었네요 . 고생하셨습니다~ 
그리구 파일명이 아직 변경이 안된 것 같습니다!

2021-02-09 15:04 UTC, dev-Lena commented
파일 이름 변경하고 피드백 주신 부분 모두 반영했습니다!
@seizze  확인 후 approve 부탁드려요!

2021-02-10 03:19 UTC, seizze approved these changes
수고하셨습니다~~👏👏👏
스위프트는 기본 컬렉션 타입들이 제네릭으로 이루어져 있어서 자바처럼 내부적으로 Object 타입을 갖도록 만들지 않아도 되고, 내부적으로도 제네릭 타입 파라미터와 같은 타입을 사용할 수 있다는 점이 좋은 것 같아요~

2021-02-10 06:17 UTC, merged