item36. 비트 필드 대신 EnumSet을 사용하라
TheSwiftists/effective-swift pull request #70
Opened 2021-01-03 06:38 UTC by gwonii

item36 초안 작성 내용입니다.

2021-01-16 05:17 UTC, delmaSong approved these changes
잘 정리해주셔서 OptionSet, RawRepresentable, EnumSet에 대해 많이 알아가네요 ㅎㅎ 
수고하셨습니다 👏🏼

2021-01-16 05:17 UTC, delmaSong commented on 6장_열거_타입과_애너테이션/Item 36. 비트 필드 대신 EnumSet을 사용하라.md
> +
-니다 로 수정했습니다
```suggestion

먼저 **Swift** 에서는 **java** 와 같이 비트 벡터를 기반으로 작성된 `EnumSet`과 같은 타입은 존재하지 않습니다. 하지만 **Swift** 에서는 `OptionSet` 이라는 타입이 존재합니다. 

```

2021-01-16 06:20 UTC, delmaSong commented
아 그리고 md 파일 이름은 item36.md 로 수정부탁드려요!

2021-02-12 04:12 UTC, dev-Lena approved these changes
덕분에 자바의 `EnumSet`와 스위프트`OptionSet`, `RawRepresentable`에 대해 알게 됐습니다! 감사합니다! 👍🏻

P.S.아래 코멘트 겸 질문 하나 남겼습니다!

2021-02-12 04:12 UTC, dev-Lena commented on 6장_열거_타입과_애너테이션/Item36.md
> +`OptionSet`을 사용할 때는 보통 `struct` 를 사용하는 것으로 보여진다. 그런데 이렇게 `Struct` 에 `OptionSet` 을 채택해서 사용하는 경우 필드들을 직접 순회할 수 없습니다.
이 문장의 서술어를 바꾸면 좋을 것 같아요! 🙌🏻

```suggestion
`OptionSet`을 사용할 때는 보통 `struct` 를 사용하는 것으로 보여집니다. 그런데 이렇게 `Struct` 에 `OptionSet` 을 채택해서 사용하는 경우 필드들을 직접 순회할 수 없습니다. 
```

그리고 
🆀. `OptionSet` 을 채택해서 사용하는 경우 필드들을 직접 순회할 수 없음에도 OptionSet을 struct로 보통 사용하는 이유가 있는지 궁금합니다!🧐

2021-02-12 12:51 UTC, Limwin94 approved these changes
어려운 내용 정리하시느라 고생하셨습니다! 
실제로 비트관련되서 다루는 일이 없어서 더 어렵게 느껴졌던것 같습니다.

오타 수정만 한번 부탁드릴게요 :)

2021-02-12 12:51 UTC, Limwin94 commented on 6장_열거_타입과_애너테이션/Item36.md
> +직접 `Sequence` 와 `ItertorProtocol` 을 이용해서 **Iterator**를 만들어야 합니다.
`ItertorProtocol `-> `IteratorProtocol` 
오타 수정 부탁드릴게요!

2021-02-21 14:42 UTC, seizze approved these changes
수고 많으셨습니다! Option의 요소들을 순회하는 방법은 정말 꿀팁인 것 같습니다 👍👍

그리고 파일명이 소문자로 아직 안바뀌어 있어서 제가 바꿨습니다!

2021-02-21 14:42 UTC, seizze commented on 6장_열거_타입과_애너테이션/Item36.md
> +먼저 **Swift** 에서는 **java** 와 같이 비트 벡터를 기반으로 작성된 `EnumSet`과 같은 타입은 존재하지 않습니다. 하지만 **Swift** 에서는 `OptionSet` 이라는 타입이 존재합니다.
[Swift OptionSet 문서](https://developer.apple.com/documentation/swift/optionset)에서 rawValue를 비트 시프트 연산으로 선언하고 있고, 타입 설명에도 bit set에 대한 set 인터페이스를 제공하고 있다고 쓰여 있는 것으로 볼 때, 내부적으로는 비트 벡터를 사용해 데이터를 표현하고 있지 않나 하는 추측이 듭니다. 그래야 모든 옵션 조합들을 유일한 값으로 표현할 수 있으니까요!

2021-02-21 14:42 UTC, seizze commented on 6장_열거_타입과_애너테이션/Item36.md
> +먼저 **Swift** 에서는 **java** 와 같이 비트 벡터를 기반으로 작성된 `EnumSet`과 같은 타입은 존재하지 않습니다. 하지만 **Swift** 에서는 `OptionSet` 이라는 타입이 존재합니다.
참고 자료에 포함해주신 swiftrocks.com의 글을 보다보니까 NS_OPTIONS을 브릿징한 게 OptionSet이고, OptionSet에서 비트 마스킹 연산을 알아서 해 준다고 써 있네요~ 내부적으로는 비트 벡터로 표현하고 있는 게 맞는것 같습니다 ㅎㅎ

2021-05-02 07:31 UTC, ehgud0670 requested changes
* OptionSet의 존재를 알려주셔서 감사합니다. 
* 그리고 또한 어떻게 하면 순회할 수 있는지 IteratorProtocol 등등의 방법도 잘 봤습니다. 매우 유익하네요 👍
* 하지만 Option의 의미는 잘 모르겠습니다(블로그를 보아도...). 그냥 효율은 생각하지 않고 따라 만든 것 같은뎁.. 뭐가 좋은지 설명 부탁드립니다..!

2021-05-02 07:31 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item36.md
> +            defer { bitMask = bitMask &* 2 }
bitMask * 2 가 맞는거겟죠? 
&* 연산자는 찾아보니 없어서요. 근데 돌아가는게 신기하네요 ㅋㅋㅋ

2021-05-02 07:31 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item36.md
> +```swift
EnumSet이나 OptionSet도 내부의 비트 벡터를 통해  데이터를 효율적으로 사용하기 위해 나타났습니다(비트 필드도 그렇고요).
근데 이 ShippingOptions는 효율적으로 어떤 점이 좋아서 쓰는지 모르겠네여. 알려주세요 ㅎㅎㅎ

2021-05-02 07:31 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item36.md
> +}
이렇게 비트 값을 합친 rawValue 어디다가 쓸 수 있나요? 
그리고 해당 원소들이 실제로 비트 값(ex: 1111 = 0001 + 0010+ 0100+ 1000)대로 저장되어 있지 않는것 같은데 이 rawValue가 어떤 의미가 있는지 궁금합니다..!

2021-05-13 03:02 UTC, delmaSong commented on 6장_열거_타입과_애너테이션/item36.md
> +
`OptionSet`을 순회하기 위해 `Enum 확장해서 사용하기` 방법을 사용해보니까 `OptionSet`의 기능은 들어가있지 않은 것 같아요..! 제공된 방법은 그냥 `Enum`을 순회하는 방법인 것 같은데 제가 잘못 사용한 걸까요?

2023-03-01 06:24 UTC, merged