item40. @Override 애너테이션을 일관되게 사용하라
TheSwiftists/effective-swift pull request #71
Opened 2021-01-03 08:30 UTC by delmaSong

java에서 @Override 애너테이션을 사용해야하는 이유와
swift에서 override 키워드를 사용해야하는 이유에 대해 정리했습니다

2021-01-09 04:32 UTC, seizze approved these changes
깔끔하게 잘 정리해주셨네요! 수고하셨습니다~~👏👏👏

2021-01-09 06:05 UTC, dev-Lena approved these changes
수고하셨습니다! 🙌🏻

2021-01-09 08:40 UTC, ehgud0670 approved these changes
좋은 내용 잘 읽었습니다. 감사합니다~ 👍

2021-01-11 06:49 UTC, Limwin94 requested changes

2021-01-11 06:49 UTC, Limwin94 commented on 6장_열거_타입과_애너테이션/item40.md
> +SubClass가 SubClass를 상속받고 있고 타입만 다른 메서드를 재정의하려고 합니다. 하지만 다른 타입의 파라미터를 지정함으로 재정의(overriding)된 것이 아니라 다중정의(overloading)되어버렸습니다.
`SubClass`가 `SuperClass`를 ~ 같습니다.

2021-01-11 10:51 UTC, delmaSong commented on 6장_열거_타입과_애너테이션/item40.md
> +SubClass가 SubClass를 상속받고 있고 타입만 다른 메서드를 재정의하려고 합니다. 하지만 다른 타입의 파라미터를 지정함으로 재정의(overriding)된 것이 아니라 다중정의(overloading)되어버렸습니다.
```suggestion
SubClass가 SuperClass를 상속받고 있고 타입만 다른 메서드를 재정의하려고 합니다. 하지만 다른 타입의 파라미터를 지정함으로 재정의(overriding)된 것이 아니라 다중정의(overloading)되어버렸습니다. 
```

2021-01-11 16:05 UTC, ehgud0670 approved these changes

2021-01-17 12:41 UTC, gwonii approved these changes
정리가 깔끔하신 것 같습니다. 고생하셨습니다~

2021-01-17 13:53 UTC, Limwin94 approved these changes
고생하셨습니다!

2021-01-17 14:45 UTC, merged