item 34. int 상수 대신 열거 타입을 사용하라
TheSwiftists/effective-swift pull request #74
Opened 2021-01-08 08:17 UTC by dev-Lena

Java에서의 열거타입
- 열거 타입(Enumerations)이 있기 이전의 문제점 설명
- Java에서의 열거타입(Enumerations) 설명

Swift에서의 열거 타입(Enumerations)
- C 또는 Objective-C vs Swift
- Swift의 Enum의 특징
- enum의 raw value 지정 규칙
- enum의 모든 경우를 순회하고 싶을 때
- Associated Value(연관 값)
- 열거 타입을 사용하는 경우
- 열거 타입을 사용을 권장하지 않는 경우

2021-01-09 08:34 UTC, ehgud0670 requested changes
네, 좋은 글 잘 읽었습니다~! 
고생하셨습니다. 👏

2021-01-09 08:34 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item34.md
> +3. Swift에서는 열거 타입은 case 값으로 string`, `character`, `integer`, `floting 타입을 사용할 수 있습니다.
```suggestion
3. Swift에서는 열거 타입은 case 값으로 `string`, `character`, `integer`, `floting` 타입을 사용할 수 있습니다. 
```
=> ` 빠진 곳 추가하였습니다~

2021-01-09 08:34 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item34.md
> +  case professor(name:String, age:int)
```suggestion
    case student(name:String, birthday:String, age:int)
    case professor(name:String, age:int)
```
=> 인덴트 수정하였습니다~

2021-01-09 08:34 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item34.md
> +### Swift에서의 열거 타입(Enumerations)
아까 말씀드린것처럼 책의 코드 34-8의 문제를 코드34-9 처럼 전략 열거 타입 패턴으로 해결한 내용을 스위프트 코드로 추가해주시면 좋을 것 같습니다!

2021-01-16 06:01 UTC, delmaSong requested changes
Enum에 대해 잘 정리하셨네요!
책에 나온 전략 열거 타입 패턴 부분만 보충되면 좋겠습니다
수고하셨습니다! 😀

2021-01-16 06:01 UTC, delmaSong commented on 6장_열거_타입과_애너테이션/item34.md
> +저자는 필요한 원소를 컴파일 타임에 다 알 수 있는 상수 집합이라면 항상 열거 타입을 사용하라고 권고하고 있습니다. 또한 열거 타입은 나중에 상수가 추가 되어도 바이너리 수준에서 호환되로록 설계되었기 때문에 열거 타입에 정의된 상수 개수가 영원히 고정 불변일 필요는 없습니다.
오타 수정했습니다
```suggestion
저자는 필요한 원소를 컴파일 타임에 다 알 수 있는 상수 집합이라면 항상 열거 타입을 사용하라고 권고하고 있습니다. 또한 열거 타입은 나중에 상수가 추가 되어도 바이너리 수준에서 호환되도록 설계되었기 때문에 열거 타입에 정의된 상수 개수가 영원히 고정 불변일 필요는 없습니다.
```

2021-01-16 06:01 UTC, delmaSong commented on 6장_열거_타입과_애너테이션/item34.md
> +> 이는 열거형 각각이 고유의 타입으로 인식될 수 없다는 문제 때문에 여러 열거형을 사용할 때 프로그래멍의 실수로 인한 버그가 생길 수도 있습니다.
오타 정정했습니다
```suggestion
> 이는 열거형 각각이 고유의 타입으로 인식될 수 없다는 문제 때문에 여러 열거형을 사용할 때 프로그래밍의 실수로 인한 버그가 생길 수도 있습니다. 
```

2021-01-16 06:01 UTC, delmaSong commented on 6장_열거_타입과_애너테이션/item34.md
> +### Swift에서의 열거 타입(Enumerations)
저도 Swift의 전략 열거 타입 패턴 부분만 보충되면 좋겠습니다 🙏🏻

2021-02-09 14:54 UTC, dev-Lena commented
@ehgud0670 @delmaSong 
전략 열거 패턴 (The strategy enum pattern) 예제를 Swift로 바꾼 내용을 추가했습니다! 

한번 확인 부탁드립니다!

2021-02-11 02:32 UTC, Limwin94 approved these changes
고생하셨습니다! 전략 열거 패턴에 대해서도 잘 읽어보았습니다 :)

2021-02-11 02:32 UTC, Limwin94 commented on 6장_열거_타입과_애너테이션/item34.md
> +> 이는 열거형 각각이 고유의 타입으로 인식될 수 없다는 문제 때문에 여러 열거형을 사용할 때 프로그래밍의 실수로 인한 버그가 생길 수도 있습니다.
스위프트를 제외한 언어에서의 해당인가요?

2021-02-11 03:17 UTC, dev-Lena commented on 6장_열거_타입과_애너테이션/item34.md
> +> 이는 열거형 각각이 고유의 타입으로 인식될 수 없다는 문제 때문에 여러 열거형을 사용할 때 프로그래밍의 실수로 인한 버그가 생길 수도 있습니다.
아 기존의 C언어 등에 대한 언어에 해당하는 이야기 입니다!! 👀

아래는 책(스위프트 프로그래밍 Swift5 3판(지은이: 야곰) 4.5 열거형) 본문에 ... 앞문장입니다.

> 기존의 C언어 등에서의 열거형은 주로 정수 타입 값의 별칭 형태로 사용될 뿐이었습니다

2021-02-12 09:07 UTC, gwonii approved these changes
내용을 보다보니 "enum은 생성자를 가질 수 있다."  문구를 보고 enum init을 할 수 있다는 사실을 알게 되었습니다.... 
정리하시느라 고생많으셨습니다!

2021-02-12 14:37 UTC, ehgud0670 requested changes
피드백 수정 감사합니다! 👏👏 한번 더 확인 부탁드립니다!! 🙏

2021-02-12 14:37 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item34.md
> +  case professor(name:String, age:int)
```Swift
enum School {
    case student(name:String, birthday:String, age:Int)
    case professor(name:String, age:Int)
}
```

=> 아직 수정이 안되어 다시 제안합니다! 그리고 int에서 Int로 추가 수정하였습니다.

2021-02-12 14:37 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item34.md
> +  }
```suggestion
// 코드 34-8를 Swift로 변환
enum PayrollDay {
    case MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY
    static private var MINS_PER_SHIFT: Int = 8 * 60 // enums must not contatin stored properties
    func pay(minutesWorked: Int, payRate: Int)-> Int {
        let basePay: Int = minutesWorked * payRate
        var overtimePay: Int
        switch(self) {
        case .SATURDAY, .SUNDAY: // Weekend
            overtimePay = basePay / 2;
            break;
        default: // Weekday
            overtimePay =
                minutesWorked <= PayrollDay.MINS_PER_SHIFT ?
                    0 : (minutesWorked - PayrollDay.MINS_PER_SHIFT) * payRate / 2
        }
        return basePay + overtimePay
    }
}
```
=> xcode로 옮겨서 인덴트 정리하고 basePay도 let으로 수정하였습니당

2021-02-12 14:37 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item34.md
> +weekdayPay.pay(minutesWorked: 1500, payRate: 2) // 1020
해당 부분 아래처럼 제안해봅니다. `private init` 과 `static let`을 사용해 자바 Enum 과 유사하게 사용되게끔 하였습니다.
꼭 아래처럼은 아니더라도 PayrollDay의 MONDAY 부터 SUNDAY 까지 case 구문이 계속 있는 형태로 있으면 좋겠습니다!
덧붙여, 위의 코드는 `basePay`와 `overtimePay`가 생략되어 있는 것 같아 추가하였습니다.
좋은 아이디어 감사합니다 👍👍👍

```Swift
struct PayrollDay {
    static let monday = PayrollDay(.WEEKDAY)
    static let tuesday = PayrollDay(.WEEKDAY)
    static let wednesday = PayrollDay(.WEEKDAY)
    static let thursday = PayrollDay(.WEEKDAY)
    static let friday = PayrollDay(.WEEKDAY)
    static let saturday = PayrollDay(.WEEKEND)
    static let sunday = PayrollDay(.WEEKEND)

    private let payType: PayType
    private static var MINS_PER_SHIFT = 8 * 60

    private init(_ payType: PayType) {
        self.payType = payType
    }

    func pay(minutesWorked: Int, payRate: Int) -> Int {
        return payType.pay(minsWorked: minutesWorked, payRate: payRate)
    }

    enum PayType {
        case WEEKDAY, WEEKEND

        func pay(minsWorked: Int, payRate: Int) -> Int {
            let basePay = minsWorked * payRate
            return basePay + overtimePay(minsWorked: minsWorked, payRate: payRate)
        }
        
        private func overtimePay(minsWorked: Int, payRate: Int) -> Int {
            switch self {
            case .WEEKDAY:
                return minsWorked <= PayrollDay.MINS_PER_SHIFT ?
                    0 : (minsWorked - PayrollDay.MINS_PER_SHIFT) * payRate / 2
            case .WEEKEND:
                return minsWorked * payRate / 2
            }
        }
    }
}

let curPayrollDay: PayrollDay = .monday
```

2021-02-27 21:21 UTC, seizze commented on 6장_열거_타입과_애너테이션/item34.md
> +weekdayPay.pay(minutesWorked: 1500, payRate: 2) // 1020
저도 이 방법 좋은 것 같습니다. 책에서 예시로 든 API가 클라이언트 측에서 일당을 요청했을 때 요일에 따라 이를 계산해주는 기능이기 때문에 요일을 고르는 절차가 필요한것 같아요! 제이슨이 제안한 방법대로면 클라이언트 측에서 요일을 고를 수도 있고, 생성자를 private으로 선언해서 기존 enum과 같이 case를 제한할 수도 있어서 좋은 것 같습니다.

다만 모든 case를 순회하거나 모든 case의 개수를 구할 수는 없는데, 이에 대비해 CaseIterable 프로토콜을 구현해 놓으면 모든 case를 순회할 수도 있고, case의 개수도 구할 수 있을 것 같아요.

```swift
struct PayrollDay: CaseIterable {
    typealias AllCases = [PayrollDay]
    
    static var allCases: [PayrollDay] {
        return [monday, tuesday, wednesday, thursday, friday, saturday, sunday]
    }
}
```

2021-02-27 21:22 UTC, seizze commented on 6장_열거_타입과_애너테이션/item34.md
> +weekdayPay.pay(minutesWorked: 1500, payRate: 2) // 1020
추가로 책에서 switch문을 지양하고 있어서 저도 switch를 빼기 위해 프로토콜을 사용해서 추상화해 봤는데 이렇게도 가능하네요 ㅎㅎ 하지만 스위프트에서는 switch문에서 모든 case를 처리하지 않을 때 컴파일 에러로 알려주기 때문에 PayType이 enum이어도 저는 충분하다고 생각하긴 합니다. 새 payType이 추가됐을 때 case를 수정하지 않을 방법이 필요하다면 이 방법을 쓰면 좋을 것 같아요~

그리고 만약 책에서 나온 상수별 메서드 구현과 같은 기능이 필요하다면 이런 식으로 구현할 수도 있을듯!

```swift
private protocol PayType {
    func pay(minutesWorked: Int, payRate: Int) -> Int
    func overtimePay(minutesWorked: Int, payRate: Int) -> Int
}

private extension PayType {
    func pay(minutesWorked: Int, payRate: Int) -> Int {
        let basePay = minutesWorked * payRate
        return basePay + overtimePay(minutesWorked: minutesWorked, payRate: payRate)
    }
}

struct PayrollDay {
    private struct Weekday: PayType {
        func overtimePay(minutesWorked: Int, payRate: Int) -> Int {
            let minutesPerShift = 480
            return minutesWorked <= minutesPerShift ? 0 : (minutesWorked - minutesPerShift) * payRate / 2
        }
    }
    
    private struct Weekend: PayType {
        func overtimePay(minutesWorked: Int, payRate: Int) -> Int {
            return minutesWorked * payRate / 2
        }
    }
    
    static let monday = PayrollDay(payType: Weekday())
    static let tuesday = PayrollDay(payType: Weekday())
    static let wednesday = PayrollDay(payType: Weekday())
    static let thursday = PayrollDay(payType: Weekday())
    static let friday = PayrollDay(payType: Weekday())
    static let saturday = PayrollDay(payType: Weekend())
    static let sunday = PayrollDay(payType: Weekend())
    
    private let payType: PayType
    
    private init(payType: PayType) {
        self.payType = payType
    }
    
    func pay(minutesWorked: Int, payRate: Int) -> Int {
        return payType.pay(minutesWorked: minutesWorked, payRate: payRate)
    }
}

// 시급 9000원, 일요일 4시간 근무 -> 54000원
PayrollDay.sunday.pay(minutesWorked: 4 * 60, payRate: 9000 / 60)
```

2021-02-27 21:23 UTC, seizze commented on 6장_열거_타입과_애너테이션/item34.md
> +weekdayPay.pay(minutesWorked: 1500, payRate: 2) // 1020
그리고 자바에서는 상수를 모두 대문자로 쓰고 있는데, 저는 스위프트에서 권장하는 방식에 따라서 lower 카멜 케이스를 쓰는 편이 더 좋은것 같다고 생각합니다.

2021-02-27 21:24 UTC, seizze approved these changes
다른 분들이 확인 후 승인해 주시면 될것 같아서 저는 approve 하겠습니다~
수고하셨습니다~~👏👏👏

2021-05-31 14:54 UTC, dev-Lena commented on 6장_열거_타입과_애너테이션/item34.md
> +weekdayPay.pay(minutesWorked: 1500, payRate: 2) // 1020
오우 피드백과 제안 감사합니다! 제가 기존에 바꿨던 코드의 문제점과 두 분의 제안 사항을 같이 확인하면 좋을 것 같아서 기존 코드를 남겨두고 아래에 두 분의 제안 코드를 문서에 추가하였습니다!!

2021-05-31 14:58 UTC, ehgud0670 commented
정말 고생하셨습니다. 👍
내용이 너무 알차고 좋습니다! 
전략 열거 패턴도 Swift 스타일로 변환도 하시고 열정이네요! 🔥
글 잘 읽었어요~ 🙇‍♂️

2021-05-31 14:58 UTC, ehgud0670 approved these changes
정말 고생하셨습니다. 👍
내용이 너무 알차고 좋습니다! 
전략 열거 패턴도 Swift 스타일로 변환도 하시고 열정이네요! 🔥
글 잘 읽었어요~ 🙇‍♂️

2021-05-31 15:22 UTC, merged