item37. ordinal 인덱싱 대신 EnumMap을 사용하라
TheSwiftists/effective-swift pull request #75
Opened 2021-01-08 10:30 UTC by dev-Lena

### 아이템 요약
- 자바에서 ordinal 메서드로 인덱싱을 하지 말아야 하는 이유 설명
- 권장 방법(EnumMap) 소개

### Swift에서 EnumMap 사용 예시 - Fonts Dictionary
- enum만 사용했을 때
- CaseItable를 사용했을 때
- 추가로 EnumMap을 직접 구현하여 사용했을 때

2021-01-09 13:34 UTC, delmaSong approved these changes
생소한 EnumMap이 무엇인지, 실질적으로 어떻게 사용할 수 있는지 알 수 있었습니다 수고하셨습니다👍🏼

2021-02-12 13:05 UTC, Limwin94 approved these changes
응용하는 과정이 코드에 있어서 EnumMap에 대해서 더 이해하기 쉬웠습니다. 고생하셨습니다.

2021-02-16 13:55 UTC, gwonii approved these changes
좋은 내용 감사합니다!

2021-02-16 13:55 UTC, gwonii commented on 6장_열거_타입과_애너테이션/item37.md
> +}
여기서 정의하고 있는 textStyle 들은 enum 안에서 표현하는게 더 깔끔한 것 같습니다! 
enum에서 연산프로퍼티를 이용해서 textStyle을 가지고 있는다면 
```
let fonts EnumMap<TextType, UIFont> { .perferredFont(forTextStyle: $0.textType) } 
```
처럼 구현할 수 있을 것 같습니다. 

그리고 TextType이 자신의 TextStyle을 갖고 있는 것이 의미적으로도 좋지 않나 싶네요~

2021-02-18 08:36 UTC, ehgud0670 requested changes
수고하셨습니다!! Swift 버전으로 EnumMap 구현하신 내용 
매우 기발하고 활용하기 좋네요! CaseIterable 내용도 좋았습니다. 💯
좋은 내용 감사합니다!! 👏👏👏

2021-02-18 08:36 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item37.md
> +
아이템 37의 코드 37-5 부터 37-7까지를 스위프트 버전으로 바꾸어 추가 설명 제안합니다!
제안드리는 이유는 EnumMap을 효과적으로 사용하는 예제 내용이기 때문입니다.
그리고 제가 내용 추가하고 싶은데, 제가 내용 추가할까요?

2021-02-20 02:13 UTC, dev-Lena commented on 6장_열거_타입과_애너테이션/item37.md
> +
아 네네! 책에 있는 EnumMap 예시가 추가되면 더 좋겠네요! 좋습니다! 내용 추가 부탁드려요! 🤓

2021-02-21 14:51 UTC, ehgud0670 approved these changes
내용 추가하였습니다. 
설명해주신 EnumMap Swift 버전이 제일 깔끔하고 좋네요, 잘 사용할 수 있을 것 같아요 👍
좋은 글 감사합니다! 👏

2021-05-31 15:24 UTC, merged