Item39. 명명패턴보단 애너테이션을 사용하라
TheSwiftists/effective-swift pull request #76
Opened 2021-01-08 14:57 UTC by delmaSong

Java의 명명패턴과 애너테이션
Swift의 Attributes에 대해 알아봅니다

2021-01-11 16:01 UTC, ehgud0670 requested changes
머지 할땐 하더라도 `@testable` 하나 추가하는 것 정돈 괜찮을 것 같습니다 ㅎㅎ

2021-01-11 16:01 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item39.md
> +
넵, 말씀들은대로 명명타입에 대한 검사 어노테이션은 스위프트는 따로 없다는것은 알겠습니다!
대신 @testable 에 대한 설명 추가는 어떠신가요?

* 찾아보니 @testable로 앱 코드나 프레임워크를 임포트하면 internal or public 클래스를 open 접근으로 사용 가능하고, 다른 앤티티(struct 등등)의 경우에는 internal 한 엔티티를 public 하게 사용할 수 있다고 합니다.

> When you add the @testable attribute to an import statement for a module compiled with testing enabled, you activate the elevated access for that module in that scope. Classes and class members marked as internal or public behave as if they were marked open. Other entities marked as internal act as if they were declared public.

출처: https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/04-writing_tests.html

* 그리고 zedd가 말하길 Build Setting의 Enable Testability를 Yes로 해야 @testable이 잘 적용된다고 합니다

출처: https://zeddios.tistory.com/1078

확입 부탁드립니다~!!

2021-01-15 14:30 UTC, delmaSong commented on 6장_열거_타입과_애너테이션/item39.md
> +
말씀하신 내용 보충했습니다 감사합니다 👏🏼

2021-01-15 15:04 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item39.md
> +또한 별표(\*)를 사용해 모든 플랫폼 이름에서 선언이 가능함을 나타낼 수 있습니다. 하지만 swift의 버전 번호를 이용해 구체적인 가용성을 나타내기 위해서 별표(\*)는 사용되지 않습니다.
```suggestion
또한 별표(\*)를 사용해 모든 플랫폼 이름에서 선언이 가능함을 나타낼 수 있습니다. 하지만 플랫폼 이름과 달리 Swift는 버전 번호를 이용해 구체적인 가용성을 나타내기 위해서 별표(\*)는 사용되지 않습니다.
```
지금 읽고 있는데 이렇게 바꾸면 더 잘 읽혀지는 것 같아 제안합니다~

2021-01-15 15:32 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item39.md
> +또한 별표(\*)를 사용해 모든 플랫폼 이름에서 선언이 가능함을 나타낼 수 있습니다. 하지만 swift의 버전 번호를 이용해 구체적인 가용성을 나타내기 위해서 별표(\*)는 사용되지 않습니다.
처음 읽기에는 그냥 @available을 사용할 때 general하게 별표(\*) 사용이 된다고 했다가, 갑자기 별표(\*)는 사용되지 않는다고 읽혀져서요~ 
그래서 비교되도록 위와 같이 제안합니다.

2021-01-15 15:43 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item39.md
> +
해당 내용 코드와 함께 제가 추가해도 될까요? 흥미롭네여 
(https://medium.com/swiftify/enum-in-swift-5-19b324b25f94)

2021-01-16 03:13 UTC, delmaSong commented on 6장_열거_타입과_애너테이션/item39.md
> +
네 그렇게 해주세요

2021-01-17 08:39 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item39.md
> +
Frozen도 할게요 오늘안에 추가하겠습니다! 정말로요 ㅎㅎ

2021-01-17 18:07 UTC, seizze commented
로컬 main 브랜치가 origin/main을 받아오지 않은채로 머지돼서 자꾸 충돌이 나거나 문제가 생기는거 같아요
(혹시 뭔가 꼬였다면 참고하세여..ㅎㅎ)

2021-01-18 01:02 UTC, ehgud0670 commented on 6장_열거_타입과_애너테이션/item39.md
> +## Attribute related to Library Evolution Mode
frozen 과 unknown attribute 를 추가했습니다. 
이해가 안되거나 잘못된 부분 있으면 말씀 부탁드립니다~!

2021-02-06 10:22 UTC, delmaSong commented
@ehgud0670 내용 추가는 완료된 것인가요?

2021-02-06 11:29 UTC, ehgud0670 commented
넵

2021-02-12 13:17 UTC, Limwin94 approved these changes
코멘트 하나 남기긴했는데 제안 정도라,,ㅎㅎ 한번 읽어보시면될것 같습니다. 고생하셨습니다!

2021-02-12 13:17 UTC, Limwin94 commented on 6장_열거_타입과_애너테이션/item39.md
> +  @available(iOS, deprecated: 9.0)
`특정 버전'부터'` 혹은 `특정 버전'에서 부터'`가 더 자연스러운것 같습니다...!

2021-02-12 13:17 UTC, Limwin94 commented on 6장_열거_타입과_애너테이션/item39.md
> +  @available(iOS, deprecated: 9.0)
표시되는 버전이 해당 버전부터(쓰이지 않게 시작한 첫번째 버전을 명시) 쓰이지 않는다고 지시하는것이라 해당 문구가 더 자연스럽다고 생각되어 의견내보았습니다!

2021-02-12 13:17 UTC, Limwin94 commented on 6장_열거_타입과_애너테이션/item39.md
> +
FrozenEnum은 처음들어보네요 고생하셨습니다~!

2021-02-12 14:41 UTC, ehgud0670 approved these changes
수고하셨습니다! 👏👏👏
Swift 의 애너테이션에 대해 많은 걸 알아갑니다.
감사합니다! 👍

2021-02-16 14:11 UTC, gwonii approved these changes
감사합니다. 덕분에 다양한 Attribute 들을 알게되었습니다~

2021-02-16 14:11 UTC, gwonii commented on 6장_열거_타입과_애너테이션/item39.md
> +Java의 테스트 메서드에 `test-` 접두사가 붙어야 했던 것처럼 iOS 앱 개발시 유닛테스트 메소드에도 `test-` 접두사가 붙어야만 테스트 메소드로 인지합니다. (그 외에도 테스트 메서드는 인자와 리턴 값이 없어야 한다는 조건이 있습니다.) 하지만 Swift에는 Java처럼 테스트에서의 명명패턴을 대체할 수 있는 기능이 없습니다.(혹여 제가 잘못
제가 의미를 정확히 이해한지는 모르겠으나 @propertyWrapper 를 통해서 애너테이션을 직접 만들어서 사용할 수 있습니다! 
필요한 부분이 생겨서 만들어 사용한 적이 있는데, 하단 코드입니다. 

만약 글의 의도와 달랐다면 죄송합니다. 허허
```
@propertyWrapper class ThreadSafe<Value> {
    var dispatchQueue: DispatchQueue

    private var value: Value
    var wrappedValue: Value {
        get {
            return self.dispatchQueue.sync {
                return self.value
            }
        }
        set {
            self.dispatchQueue.sync {
                self.value = newValue
            }
        }
    }

    init(wrappedValue: Value, dispatchQueue: DispatchQueue = .global()) {
        self.value = wrappedValue
        self.dispatchQueue = dispatchQueue
    }
}

extension ThreadSafe: Equatable where Value: Equatable {
    static func == (lhs: ThreadSafe<Value>, rhs: ThreadSafe<Value>) -> Bool {
        return lhs.value == rhs.value
    }

    static func == (lhs: ThreadSafe<Value>, rhs: Value) -> Bool {
        return lhs.value == rhs
    }

    static func == (lhs: Value, rhs: ThreadSafe<Value>) -> Bool {
        return lhs == rhs.value
    }
}
```

사용할 때는 필요한 부분에 기존의 애너테이션과 동일하게 사용하면 됩니다!
```
    @ThreadSafe
    private(set) var isBusy: Bool = false
```

그리고 `test-` 를 대신할 수 있는 방법이 있는지는 한 번 실험을 해봐야할 것 같습니다.

2021-02-20 07:12 UTC, dev-Lena approved these changes
덕분에 다양한 Attributes에 대해서 알아갑니다! Swift 코드를 열어보면서 @frozen이 궁금했는데 Attribute related to Library Evolution Mode 에서 다뤄주신 덕분에 더 알아갑니다! 감사합니다! 수고 많이하셨습니다! 🤩✨👍🏻

2021-06-02 00:21 UTC, merged