item49. 매개변수가 유효한지 검사하라
TheSwiftists/effective-swift pull request #86
Opened 2021-01-22 15:24 UTC by delmaSong

자바의 내용을 다루지 않아도 될정도의 범용적인 내용이라 스위프트에 조금 더 초점을 맞추어 작성했습니다.

2021-02-12 13:25 UTC, Limwin94 approved these changes
메서드 깎는 개발자에 한발짝 더 가까워진것 같습니다. 문서 감사합니다.

2021-02-15 12:52 UTC, ehgud0670 requested changes
잘 읽었습니다! 💯 
피드백 확인 부탁드립니다 🙏
수고하셨습니다!! 👍👍

2021-02-15 12:52 UTC, ehgud0670 commented on 8장_메서드/item49.md
> +func mod(value: BigInteger) throws -> BigInteger {
BigInteger는 자바에서 제공되는 타입이라 Swift 예시에서 바로 쓰기에는 부자연스러워 보입니다. 
다른 타입으로 대체 부탁드립니다!

2021-02-15 12:52 UTC, ehgud0670 commented on 8장_메서드/item49.md
> +
스터디 때 말씀 드렸던것처럼 매개변수가 옵셔널 타입이고, 해당 값이 nil일때 guard let 으로  처리하는 예도 추가 부탁드립니다.

예)
```Swift
foo(value: Int?) {
  guard let value // 기타 등등
}
```

2021-02-15 12:52 UTC, ehgud0670 commented on 8장_메서드/item49.md
> +func mod(value: BigInteger) throws -> BigInteger {
mod 라는 함수가 swift 버전으로 바뀐 경우에는 
BigInteger? 로 리턴타입을 바꾸고 value가 0 보다 작거나 같을 때 nil을 반환하는 경우도 충분히 합리적일 것 같습니다.
이 경우도 함께 다루어주셨으면 합니다!

2021-02-15 12:52 UTC, ehgud0670 commented on 8장_메서드/item49.md
> +
자바처럼 Swift 도 assert 함수와 assertError가 있습니다. 해당 함수와 에러 추가 설명 부탁드립니다!!

2021-05-30 12:27 UTC, delmaSong commented on 8장_메서드/item49.md
> +func mod(value: BigInteger) throws -> BigInteger {
BigInteger를 Int로 변경하고 CalculatorError 타입 추가해 음수인경우 해당 에러 던지도록 수정했습니다
`value가 0 보다 작거나 같을 때 nil을 반환하는 경우`는 `매개변수가 유효한지`와 크게 연관이 없는 것 같아 추가하지 않았습니다

2021-05-30 12:27 UTC, delmaSong commented on 8장_메서드/item49.md
> +
매개변수가 옵셔널인 경우 에러를 던지는 상황에 대한 코드를 추가했습니다

2021-05-30 12:39 UTC, delmaSong commented on 8장_메서드/item49.md
> +
좋은 제안입니다~! 반영 완료했습니다

2021-05-30 14:06 UTC, dev-Lena approved these changes
잘 읽었습니다! 수고하셨습니다 🐝 👏🏻

2021-05-31 10:02 UTC, ehgud0670 approved these changes
수고하셨습니다 👍

2021-06-02 00:22 UTC, merged