item53. 가변인수는 신중히 사용하라 Variadic Parameters 내용 작성
TheSwiftists/effective-swift pull request #90
Opened 2021-02-05 14:55 UTC by dev-Lena

### 작성 내용
1.**`Variadic Parameters`** 소개합니다.
2. **Swift/iOS Variadic Parameters** 활용 예시를 소개합니다.
3. **`Variadic Parameters`** vs **`Array Parameters`**  언제 Variadic Parameters를 사용하면 좋을지, 언제 Array Parameters를 사용하면 좋을지 제안합니다

2021-02-09 15:13 UTC, dev-Lena commented
### 수정한 내용

스터디 때 컴파일 오류가 발생하는 예제 코드에 '컴파일 오류가 발생하는 코드'라고 명시하면 좋겠다는 의견 주셔서 추가했습니다!

2021-02-12 02:58 UTC, delmaSong approved these changes
굿 💯 수고하셨습니다

2021-02-12 04:48 UTC, delmaSong commented
리드미도 수정해주세요!

2021-02-15 13:36 UTC, ehgud0670 requested changes
* Variadic Parameters의 특징과 어떻게 사용해야 하는지 설명한 것
* Variadic Parameters 와 Array Parameters를 비교하여 설명한 것

이 특히 좋았습니다. 덕분에 잘 읽었습니다..!! 💯

피드백만 확인 부탁드립니다. 감사합니다 👍👍

2021-02-15 13:36 UTC, ehgud0670 commented on 8장_메서드/item53.md
> +> 인수 개수가 일정하지 않은 메서드를 정의해야 한다면 가변인수가 반드시 필요하다. 메서드를 정의할 때 필수 매개변수는 가변인수 앞에 두고, 가변인수를 사용할 때는 성능 문제까지 고려하자.
**코드 53-3 에 `인수가 1개 이상이어야 할 때 가변인수를 제대로 사용하는 방법`**

의 예시로 `min` 함수가 나왔는데요. 이 예제도 swift로 함께 추가 설명될까요?
제안드리는 이유는 인수 1개 이상이어야 하는 특별 케이스를 잘 다룬 예시 코드이기 때문입니다.
추가되면 문서가 더 풍부해질것 같아 제안합니다~!

* 스위프트로 바꾸어 보았습니다. 

```Swift
static func min(firstArg: Int, remainArgs: Int...) -> Int {
    var min = firstArg
    for arg in remainArgs {
        if arg < min {
            min = arg
        }
    }
    return min
}
```

감사합니다.

2021-02-16 02:44 UTC, Limwin94 approved these changes
고생하셨습니다. 유용한 내용이었습니다 :)

2021-02-19 14:05 UTC, ehgud0670 commented on 8장_메서드/item53.md
> +> 인수 개수가 일정하지 않은 메서드를 정의해야 한다면 가변인수가 반드시 필요하다. 메서드를 정의할 때 필수 매개변수는 가변인수 앞에 두고, 가변인수를 사용할 때는 성능 문제까지 고려하자.
머지전에 답변을 받고싶어 request changes를 한거지 꼭 반영해달라는 말은 아닙니다! 그리고 제가 반영해도 되구요 ㅎㅎ

2021-02-19 16:38 UTC, dev-Lena commented on 8장_메서드/item53.md
> +> 인수 개수가 일정하지 않은 메서드를 정의해야 한다면 가변인수가 반드시 필요하다. 메서드를 정의할 때 필수 매개변수는 가변인수 앞에 두고, 가변인수를 사용할 때는 성능 문제까지 고려하자.
아하! 추천 제안합니다. 👍🏻  참고해서 예시 `min` 함수 예시 코드 추가해보도록 하겠습니다!

2021-02-21 14:36 UTC, ehgud0670 commented on 8장_메서드/item53.md
> +> 인수 개수가 일정하지 않은 메서드를 정의해야 한다면 가변인수가 반드시 필요하다. 메서드를 정의할 때 필수 매개변수는 가변인수 앞에 두고, 가변인수를 사용할 때는 성능 문제까지 고려하자.
아 죄송합니다. 못 봤습니다 ㅜ 커밋 철회하도록 하겠습니다

2021-02-21 14:37 UTC, ehgud0670 commented on 8장_메서드/item53.md
> +> 인수 개수가 일정하지 않은 메서드를 정의해야 한다면 가변인수가 반드시 필요하다. 메서드를 정의할 때 필수 매개변수는 가변인수 앞에 두고, 가변인수를 사용할 때는 성능 문제까지 고려하자.
넵!!!! 감사합니다 👍

2021-02-21 14:44 UTC, ehgud0670 approved these changes
넵, 그럼 `min` 함수 예시 코드 추가 부탁드립니다. 
고생하셨습니다. 좋은 글 감사합니다. 🙇‍♂️

2021-05-31 14:41 UTC, dev-Lena commented
> 넵, 그럼 `min` 함수 예시 코드 추가 부탁드립니다.
> 고생하셨습니다. 좋은 글 감사합니다. 🙇‍♂️

늦었지만 제이슨이 제안해 준 코드 추가했습니다! 감사해요! 😃 👍🏻

2021-05-31 15:26 UTC, merged